// Auto-generated from Vanilla files configs + valid_item_sections.ltx
// Categories remapped to match vanilla debug menu (ui_debug_main.script m_classes)
window.VANILLA_ITEM_CATALOG = [
  {id:"ammo_magnum_300_bad",name:".338 Lapua Magnum",cat:"w_ammo"},
  {id:"ammo_magnum_300_verybad",name:".338 Lapua Magnum",cat:"w_ammo"},
  {id:"ammo_magnum_300",name:".338 Lapua Magnum rounds",cat:"w_ammo"},
  {id:"prt_w_p_barrel_7",name:".357 barrel",cat:"i_part"},
  {id:"ammo_357_hp_mag_bad",name:".357 HP",cat:"w_ammo"},
  {id:"ammo_357_hp_mag_verybad",name:".357 HP",cat:"w_ammo"},
  {id:"ammo_357_hp_mag",name:".357 HP rounds",cat:"w_ammo"},
  {id:"ammo_11.43x23_fmj_bad",name:".45 ACP",cat:"w_ammo"},
  {id:"ammo_11.43x23_fmj_verybad",name:".45 ACP",cat:"w_ammo"},
  {id:"ammo_11.43x23_hydro",name:".45 ACP Hydra-shock rounds",cat:"w_ammo"},
  {id:"ammo_11.43x23_fmj",name:".45 ACP rounds",cat:"w_ammo"},
  {id:"wpn_sil_45",name:".45 ACP suppressor",cat:"w_misc"},
  {id:"prt_w_p_barrel_3",name:".45 barrel",cat:"i_part"},
  {id:"ammo_11.43x23_hydro_bad",name:".45 HS",cat:"w_ammo"},
  {id:"ammo_11.43x23_hydro_verybad",name:".45 HS",cat:"w_ammo"},
  {id:"prt_w_p_spring_3",name:".45 recoil spring assembly",cat:"i_part"},
  {id:"ammo_50_bmg_bad",name:".50 BMG",cat:"w_ammo"},
  {id:"ammo_50_bmg_verybad",name:".50 BMG",cat:"w_ammo"},
  {id:"ammo_50_bmg",name:".50 BMG rounds",cat:"w_ammo"},
  {id:"drug_sleepingpills",name:"027 R pills",cat:"i_medical"},
  {id:"ammo_12.7x55_fmj_bad",name:"12.7x55",cat:"w_ammo"},
  {id:"ammo_12.7x55_fmj_verybad",name:"12.7x55",cat:"w_ammo"},
  {id:"ammo_12.7x55_ap_bad",name:"12.7x55 AP",cat:"w_ammo"},
  {id:"ammo_12.7x55_ap_verybad",name:"12.7x55 AP",cat:"w_ammo"},
  {id:"ammo_12.7x55_ap",name:"12.7x55 mm STs-130 VPS rounds",cat:"w_ammo"},
  {id:"prt_w_barrel_13",name:"12.7x55mm barrel",cat:"i_part"},
  {id:"ammo_12.7x55_fmj",name:"12.7x55mm STs-130 rounds",cat:"w_ammo"},
  {id:"ammo_12x70_buck",name:"12x70 buckshot shells",cat:"w_ammo"},
  {id:"ammo_12x70_buck_bad",name:"12x70 shot",cat:"w_ammo"},
  {id:"ammo_12x70_buck_verybad",name:"12x70 shot",cat:"w_ammo"},
  {id:"ammo_12x76_bull",name:"12x76 Bull shells",cat:"w_ammo"},
  {id:"ammo_12x76_dart",name:"12x76 dart shells",cat:"w_ammo"},
  {id:"ammo_12x76_zhekan_bad",name:"12x76 slug",cat:"w_ammo"},
  {id:"ammo_12x76_zhekan_verybad",name:"12x76 slug",cat:"w_ammo"},
  {id:"ammo_12x76_zhekan",name:"12x76 slug shells",cat:"w_ammo"},
  {id:"prt_w_barrel_3",name:"18.5mm barrel [K]",cat:"i_part"},
  {id:"prt_w_barrel_1",name:"18.5mm barrel [R]",cat:"i_part"},
  {id:"prt_w_barrel_2",name:"18.5mm barrel [R]",cat:"i_part"},
  {id:"ammo_4.6x30_fmj_bad",name:"4.6x30 FMJ",cat:"w_ammo"},
  {id:"ammo_4.6x30_fmj_verybad",name:"4.6x30 FMJ",cat:"w_ammo"},
  {id:"ammo_4.6x30_fmj",name:"4.6x30 mm FMJ rounds",cat:"w_ammo"},
  {id:"prt_w_barrel_8",name:"5.45mm barrel [�]",cat:"i_part"},
  {id:"ammo_5.45x39_ap_bad",name:"5.45x39 AP",cat:"w_ammo"},
  {id:"ammo_5.45x39_ap_verybad",name:"5.45x39 AP",cat:"w_ammo"},
  {id:"ammo_5.45x39_ep_bad",name:"5.45x39 EP",cat:"w_ammo"},
  {id:"ammo_5.45x39_ep_verybad",name:"5.45x39 EP",cat:"w_ammo"},
  {id:"ammo_5.45x39_fmj_bad",name:"5.45x39 FMJ",cat:"w_ammo"},
  {id:"ammo_5.45x39_fmj_verybad",name:"5.45x39 FMJ",cat:"w_ammo"},
  {id:"ammo_5.45x39_ap",name:"5.45x39 mm AP rounds",cat:"w_ammo"},
  {id:"ammo_5.45x39_ep",name:"5.45x39 mm EP rounds",cat:"w_ammo"},
  {id:"ammo_5.45x39_fmj",name:"5.45x39 mm FMJ rounds",cat:"w_ammo"},
  {id:"prt_w_barrel_9",name:"5.56mm barrel [�]",cat:"i_part"},
  {id:"ammo_5.56x45_ap_bad",name:"5.56x45 AP",cat:"w_ammo"},
  {id:"ammo_5.56x45_ap_verybad",name:"5.56x45 AP",cat:"w_ammo"},
  {id:"ammo_5.56x45_ss190_bad",name:"5.56x45 EP",cat:"w_ammo"},
  {id:"ammo_5.56x45_ss190_verybad",name:"5.56x45 EP",cat:"w_ammo"},
  {id:"ammo_5.56x45_fmj_bad",name:"5.56x45 FMJ",cat:"w_ammo"},
  {id:"ammo_5.56x45_fmj_verybad",name:"5.56x45 FMJ",cat:"w_ammo"},
  {id:"ammo_5.56x45_ap",name:"5.56x45 mm AP rounds",cat:"w_ammo"},
  {id:"ammo_5.56x45_ss190",name:"5.56x45 mm EP rounds",cat:"w_ammo"},
  {id:"ammo_5.56x45_fmj",name:"5.56x45 mm FMJ rounds",cat:"w_ammo"},
  {id:"prt_w_p_barrel_4",name:"5.7mm barrel",cat:"i_part"},
  {id:"ammo_5.7x28_ss190_bad",name:"5.7x28 AP",cat:"w_ammo"},
  {id:"ammo_5.7x28_ss190_verybad",name:"5.7x28 AP",cat:"w_ammo"},
  {id:"ammo_5.7x28_ss195_bad",name:"5.7x28 HP",cat:"w_ammo"},
  {id:"ammo_5.7x28_ss195_verybad",name:"5.7x28 HP",cat:"w_ammo"},
  {id:"ammo_5.7x28_ss195",name:"5.7x28 mm SS195 rounds",cat:"w_ammo"},
  {id:"ammo_5.7x28_ss190",name:"5.7x28 SS190 rounds",cat:"w_ammo"},
  {id:"wpn_sil_57",name:"5.7x28 suppressor",cat:"w_misc"},
  {id:"wpn_knife",name:"6H4 bayonet",cat:"w_melee"},
  {id:"wpn_sil_6p9",name:"6P9 suppressor",cat:"w_misc"},
  {id:"prt_w_p_barrel_5",name:"7.62mm barrel",cat:"i_part"},
  {id:"prt_w_barrel_7",name:"7.62mm barrel [A|V]",cat:"i_part"},
  {id:"prt_w_barrel_10",name:"7.62mm barrel [P]",cat:"i_part"},
  {id:"prt_w_barrel_12",name:"7.62mm barrel [PP]",cat:"i_part"},
  {id:"prt_w_barrel_4",name:"7.62mm barrel [V]",cat:"i_part"},
  {id:"prt_w_p_spring_5",name:"7.62mm recoil spring assembly",cat:"i_part"},
  {id:"ammo_7.62x25_p",name:"7.62x25 mm P rounds",cat:"w_ammo"},
  {id:"ammo_7.62x25_ps",name:"7.62x25 mm Pst rounds",cat:"w_ammo"},
  {id:"ammo_7.62x25_p_bad",name:"7.62x25 P",cat:"w_ammo"},
  {id:"ammo_7.62x25_p_verybad",name:"7.62x25 P",cat:"w_ammo"},
  {id:"ammo_7.62x25_ps_bad",name:"7.62x25 Pst",cat:"w_ammo"},
  {id:"ammo_7.62x25_ps_verybad",name:"7.62x25 Pst",cat:"w_ammo"},
  {id:"ammo_7.62x39_ap_bad",name:"7.62x39 AP",cat:"w_ammo"},
  {id:"ammo_7.62x39_ap_verybad",name:"7.62x39 AP",cat:"w_ammo"},
  {id:"ammo_7.62x39_fmj_bad",name:"7.62x39 FMJ",cat:"w_ammo"},
  {id:"ammo_7.62x39_fmj_verybad",name:"7.62x39 FMJ",cat:"w_ammo"},
  {id:"ammo_7.62x39_fmj",name:"7.62x39 mm FMJ rounds",cat:"w_ammo"},
  {id:"ammo_7.62x39_ap",name:"7.62x39 mm M43 rounds",cat:"w_ammo"},
  {id:"ammo_7.62x51_fmj_bad",name:"7.62x51 ball",cat:"w_ammo"},
  {id:"ammo_7.62x51_fmj_verybad",name:"7.62x51 ball",cat:"w_ammo"},
  {id:"ammo_7.62x51_ap",name:"7.62x51 mm NATO AP rounds",cat:"w_ammo"},
  {id:"ammo_7.62x51_ap_bad",name:"7.62x51 mm NATO AP rounds",cat:"w_ammo"},
  {id:"ammo_7.62x51_ap_verybad",name:"7.62x51 mm NATO AP rounds",cat:"w_ammo"},
  {id:"ammo_7.62x51_fmj",name:"7.62x51 mm NATO ball rounds",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h1_bad",name:"7.62x54 7N1",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h1_verybad",name:"7.62x54 7N1",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h14_bad",name:"7.62x54 7N14",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h14_verybad",name:"7.62x54 7N14",cat:"w_ammo"},
  {id:"ammo_7.62x54_ap_bad",name:"7.62x54 AP",cat:"w_ammo"},
  {id:"ammo_7.62x54_ap_verybad",name:"7.62x54 AP",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h1",name:"7.62x54 mm 7N1 rounds",cat:"w_ammo"},
  {id:"ammo_7.62x54_7h14",name:"7.62x54 mm 7N14 rounds",cat:"w_ammo"},
  {id:"ammo_7.62x54_ap",name:"7.62x54 mm AP rounds",cat:"w_ammo"},
  {id:"ammo_pkm_100",name:"7.62x54 mm PP rounds",cat:"w_ammo"},
  {id:"ammo_pkm_100_bad",name:"7.62x54 PP",cat:"w_ammo"},
  {id:"ammo_pkm_100_verybad",name:"7.62x54 PP",cat:"w_ammo"},
  {id:"ammo_7.92x33_ap_bad",name:"7.62x57 AP",cat:"w_ammo"},
  {id:"ammo_7.92x33_ap_verybad",name:"7.62x57 AP",cat:"w_ammo"},
  {id:"ammo_7.92x33_fmj_bad",name:"7.62x57 FMJ",cat:"w_ammo"},
  {id:"ammo_7.92x33_fmj_verybad",name:"7.62x57 FMJ",cat:"w_ammo"},
  {id:"prt_w_barrel_5",name:"7.92mm barrel [V]",cat:"i_part"},
  {id:"ammo_7.92x33_fmj",name:"7.92x57 mm Mauser rounds",cat:"w_ammo"},
  {id:"ammo_7.92x33_ap",name:"7.92x57 mm SA rounds",cat:"w_ammo"},
  {id:"wpn_9a91",name:"9A-91",cat:"w_smg"},
  {id:"wpn_sil_9a91",name:"9A-91/VSK-94 suppressor",cat:"w_misc"},
  {id:"prt_w_barrel_11",name:"9mm barrel [AS/PP]",cat:"i_part"},
  {id:"prt_w_barrel_6",name:"9mm barrel-silencer [AS/PP]",cat:"i_part"},
  {id:"prt_w_p_spring_2",name:"9mm recoil spring assembly [Russian]",cat:"i_part"},
  {id:"prt_w_p_spring_1",name:"9mm recoil spring assembly [Soviet]",cat:"i_part"},
  {id:"prt_w_p_spring_4",name:"9mm recoil spring assembly [Western]",cat:"i_part"},
  {id:"wpn_sil_9mm",name:"9mm suppressor",cat:"w_misc"},
  {id:"ammo_9x18_pmm_bad",name:"9x18 +P+",cat:"w_ammo"},
  {id:"ammo_9x18_pmm_verybad",name:"9x18 +P+",cat:"w_ammo"},
  {id:"ammo_9x18_fmj_bad",name:"9x18 FMJ",cat:"w_ammo"},
  {id:"ammo_9x18_fmj_verybad",name:"9x18 FMJ",cat:"w_ammo"},
  {id:"ammo_9x18_pmm",name:"9x18 mm +P+ rounds",cat:"w_ammo"},
  {id:"ammo_9x18_fmj",name:"9x18 mm FMJ rounds",cat:"w_ammo"},
  {id:"ammo_9x18_ap_bad",name:"9x18 RG028",cat:"w_ammo"},
  {id:"ammo_9x18_ap_verybad",name:"9x18 RG028",cat:"w_ammo"},
  {id:"ammo_9x18_ap",name:"9x18 RG028 rounds",cat:"w_ammo"},
  {id:"prt_w_p_barrel_1",name:"9x18mm barrel",cat:"i_part"},
  {id:"prt_w_p_barrel_6",name:"9x18mm barrel (enclosed)",cat:"i_part"},
  {id:"ammo_9x19_ap_bad",name:"9x19 AP",cat:"w_ammo"},
  {id:"ammo_9x19_ap_verybad",name:"9x19 AP",cat:"w_ammo"},
  {id:"ammo_9x19_fmj_bad",name:"9x19 FMJ",cat:"w_ammo"},
  {id:"ammo_9x19_fmj_verybad",name:"9x19 FMJ",cat:"w_ammo"},
  {id:"ammo_9x19_pbp_bad",name:"9x19 JHP",cat:"w_ammo"},
  {id:"ammo_9x19_pbp_verybad",name:"9x19 JHP",cat:"w_ammo"},
  {id:"ammo_9x19_ap",name:"9x19 mm AP rounds",cat:"w_ammo"},
  {id:"ammo_9x19_fmj",name:"9x19 mm FMJ rounds",cat:"w_ammo"},
  {id:"ammo_9x19_pbp",name:"9x19 mm JHP rounds",cat:"w_ammo"},
  {id:"prt_w_p_barrel_2",name:"9x19mm barrel",cat:"i_part"},
  {id:"ammo_9x39_pab9",name:"9x39 mm SP-5 rounds",cat:"w_ammo"},
  {id:"ammo_9x39_ap",name:"9x39 mm SP-6 rounds",cat:"w_ammo"},
  {id:"ammo_9x39_pab9_bad",name:"9x39 SP-5",cat:"w_ammo"},
  {id:"ammo_9x39_pab9_verybad",name:"9x39 SP-5",cat:"w_ammo"},
  {id:"ammo_9x39_ap_bad",name:"9x39 SP-6",cat:"w_ammo"},
  {id:"ammo_9x39_ap_verybad",name:"9x39 SP-6",cat:"w_ammo"},
  {id:"ammo_box",name:"A box of ammo",cat:"w_ammo"},
  {id:"prt_i_resistors",name:"A box of resistors",cat:"i_part"},
  {id:"prt_i_transistors",name:"A box of transistors",cat:"i_part"},
  {id:"prt_i_capacitors",name:"A pack of capacitors",cat:"i_part"},
  {id:"af_misery_bread_af_aac",name:"AAC w/ anomalous bread",cat:"i_arty"},
  {id:"af_dummy_battery_af_aac",name:"AAC w/ Battery",cat:"i_arty"},
  {id:"af_black_spray_af_aac",name:"AAC w/ Black Spray",cat:"i_arty"},
  {id:"af_bracelet_af_aac",name:"AAC w/ Bracelet",cat:"i_arty"},
  {id:"af_baloon_af_aac",name:"AAC w/ Bubble",cat:"i_arty"},
  {id:"af_compass_af_aac",name:"AAC w/ Compass",cat:"i_arty"},
  {id:"af_cristall_af_aac",name:"AAC w/ Crystal",cat:"i_arty"},
  {id:"af_death_lamp_af_aac",name:"AAC w/ Death Lamp",cat:"i_arty"},
  {id:"af_empty_af_aac",name:"AAC w/ Empty",cat:"i_arty"},
  {id:"af_eye_af_aac",name:"AAC w/ Eye",cat:"i_arty"},
  {id:"af_fireball_af_aac",name:"AAC w/ Fireball",cat:"i_arty"},
  {id:"af_glass_af_aac",name:"AAC w/ Firefly",cat:"i_arty"},
  {id:"af_fire_af_aac",name:"AAC w/ Flame",cat:"i_arty"},
  {id:"af_electra_flash_af_aac",name:"AAC w/ Flash",cat:"i_arty"},
  {id:"af_full_empty_af_aac",name:"AAC w/ Full Empty",cat:"i_arty"},
  {id:"af_gold_fish_af_aac",name:"AAC w/ Goldfish",cat:"i_arty"},
  {id:"af_gravi_af_aac",name:"AAC w/ Gravi",cat:"i_arty"},
  {id:"af_oasis_heart_af_aac",name:"AAC w/ Heart of the Oasis",cat:"i_arty"},
  {id:"af_itcher_af_aac",name:"AAC w/ Itcher",cat:"i_arty"},
  {id:"af_medusa_af_aac",name:"AAC w/ Jellyfish",cat:"i_arty"},
  {id:"af_fuzz_kolobok_af_aac",name:"AAC w/ Kolobok",cat:"i_arty"},
  {id:"af_lobster_eyes_af_aac",name:"AAC w/ Lobster Eyes",cat:"i_arty"},
  {id:"af_dummy_glassbeads_af_aac",name:"AAC w/ Mama's Beads",cat:"i_arty"},
  {id:"af_mincer_meat_af_aac",name:"AAC w/ Meat Chunk",cat:"i_arty"},
  {id:"af_electra_moonlight_af_aac",name:"AAC w/ Moonlight",cat:"i_arty"},
  {id:"af_night_star_af_aac",name:"AAC w/ Nightstar",cat:"i_arty"},
  {id:"af_pin_af_aac",name:"AAC w/ Pin",cat:"i_arty"},
  {id:"af_ring_af_aac",name:"AAC w/ Ring",cat:"i_arty"},
  {id:"af_dummy_dummy_af_aac",name:"AAC w/ Shell",cat:"i_arty"},
  {id:"af_ice_af_aac",name:"AAC w/ Snowflake",cat:"i_arty"},
  {id:"af_soul_af_aac",name:"AAC w/ Soul",cat:"i_arty"},
  {id:"af_electra_sparkler_af_aac",name:"AAC w/ Sparkler",cat:"i_arty"},
  {id:"af_sponge_af_aac",name:"AAC w/ Sponge",cat:"i_arty"},
  {id:"af_blood_af_aac",name:"AAC w/ Stone Blood",cat:"i_arty"},
  {id:"af_cristall_flower_af_aac",name:"AAC w/ Stone Flower",cat:"i_arty"},
  {id:"af_vyvert_af_aac",name:"AAC w/ Wrenched",cat:"i_arty"},
  {id:"af_misery_bread_af_aam",name:"AAM w/ anomalous bread",cat:"i_arty"},
  {id:"af_dummy_battery_af_aam",name:"AAM w/ Battery",cat:"i_arty"},
  {id:"af_black_spray_af_aam",name:"AAM w/ Black Spray",cat:"i_arty"},
  {id:"af_bracelet_af_aam",name:"AAM w/ Bracelet",cat:"i_arty"},
  {id:"af_baloon_af_aam",name:"AAM w/ Bubble",cat:"i_arty"},
  {id:"af_compass_af_aam",name:"AAM w/ Compass",cat:"i_arty"},
  {id:"af_cristall_af_aam",name:"AAM w/ Crystal",cat:"i_arty"},
  {id:"af_death_lamp_af_aam",name:"AAM w/ Death Lamp",cat:"i_arty"},
  {id:"af_empty_af_aam",name:"AAM w/ Empty",cat:"i_arty"},
  {id:"af_eye_af_aam",name:"AAM w/ Eye",cat:"i_arty"},
  {id:"af_fireball_af_aam",name:"AAM w/ Fireball",cat:"i_arty"},
  {id:"af_glass_af_aam",name:"AAM w/ Firefly",cat:"i_arty"},
  {id:"af_fire_af_aam",name:"AAM w/ Flame",cat:"i_arty"},
  {id:"af_electra_flash_af_aam",name:"AAM w/ Flash",cat:"i_arty"},
  {id:"af_full_empty_af_aam",name:"AAM w/ Full Empty",cat:"i_arty"},
  {id:"af_gold_fish_af_aam",name:"AAM w/ Goldfish",cat:"i_arty"},
  {id:"af_gravi_af_aam",name:"AAM w/ Gravi",cat:"i_arty"},
  {id:"af_oasis_heart_af_aam",name:"AAM w/ Heart of the Oasis",cat:"i_arty"},
  {id:"af_itcher_af_aam",name:"AAM w/ Itcher",cat:"i_arty"},
  {id:"af_medusa_af_aam",name:"AAM w/ Jellyfish",cat:"i_arty"},
  {id:"af_fuzz_kolobok_af_aam",name:"AAM w/ Kolobok",cat:"i_arty"},
  {id:"af_lobster_eyes_af_aam",name:"AAM w/ Lobster Eyes",cat:"i_arty"},
  {id:"af_dummy_glassbeads_af_aam",name:"AAM w/ Mama's Beads",cat:"i_arty"},
  {id:"af_mincer_meat_af_aam",name:"AAM w/ Meat Chunk",cat:"i_arty"},
  {id:"af_electra_moonlight_af_aam",name:"AAM w/ Moonlight",cat:"i_arty"},
  {id:"af_night_star_af_aam",name:"AAM w/ Nightstar",cat:"i_arty"},
  {id:"af_pin_af_aam",name:"AAM w/ Pin",cat:"i_arty"},
  {id:"af_ring_af_aam",name:"AAM w/ Ring",cat:"i_arty"},
  {id:"af_dummy_dummy_af_aam",name:"AAM w/ Shell",cat:"i_arty"},
  {id:"af_ice_af_aam",name:"AAM w/ Snowflake",cat:"i_arty"},
  {id:"af_soul_af_aam",name:"AAM w/ Soul",cat:"i_arty"},
  {id:"af_electra_sparkler_af_aam",name:"AAM w/ Sparkler",cat:"i_arty"},
  {id:"af_sponge_af_aam",name:"AAM w/ Sponge",cat:"i_arty"},
  {id:"af_blood_af_aam",name:"AAM w/ Stone Blood",cat:"i_arty"},
  {id:"af_cristall_flower_af_aam",name:"AAM w/ Stone Flower",cat:"i_arty"},
  {id:"af_vyvert_af_aam",name:"AAM w/ Wrenched",cat:"i_arty"},
  {id:"helm_ach7",name:"ACH-7 headgear set",cat:"o_helmet"},
  {id:"helm_ach7ex",name:"ACH-7EX headgear set",cat:"o_helmet"},
  {id:"wpn_addon_scope_acog_trijicon",name:"ACOG Scope",cat:"w_misc"},
  {id:"prt_o_retardant_15",name:"Activated carbon cloth (ACC) fabrics",cat:"i_part"},
  {id:"prt_o_retardant_16",name:"Active charcoal-treated non-woven fabrics",cat:"i_part"},
  {id:"itm_advancedkit",name:"Advanced tools",cat:"i_kit"},
  {id:"wpn_aek",name:"AEK-971",cat:"w_rifle"},
  {id:"wpn_aek_camo",name:"AEK-971 (Duty camouflage)",cat:"w_rifle"},
  {id:"wpn_aek_duty",name:"AEK-973",cat:"w_rifle"},
  {id:"af_ameba_mica",name:"Af Ameba Mica",cat:"i_arty"},
  {id:"af_ameba_slime",name:"Af Ameba Slime",cat:"i_arty"},
  {id:"af_ameba_slug",name:"Af Ameba Slug",cat:"i_arty"},
  {id:"af_drops",name:"Af Drops",cat:"i_arty"},
  {id:"af_dummy_pellicle",name:"Af Dummy Pellicle",cat:"i_arty"},
  {id:"af_dummy_spring",name:"Af Dummy Spring",cat:"i_arty"},
  {id:"af_quest_b14_twisted",name:"Af Quest B14 Twisted",cat:"i_arty"},
  {id:"af_quest_b14_twisted_af_aac",name:"Af Quest B14 Twisted Af Aac",cat:"i_arty"},
  {id:"af_quest_b14_twisted_af_aam",name:"Af Quest B14 Twisted Af Aam",cat:"i_arty"},
  {id:"af_quest_b14_twisted_af_iam",name:"Af Quest B14 Twisted Af Iam",cat:"i_arty"},
  {id:"af_quest_b14_twisted_lead_box",name:"Af Quest B14 Twisted Lead Box",cat:"i_arty"},
  {id:"af_rusty_kristall",name:"Af Rusty Kristall",cat:"i_arty"},
  {id:"af_rusty_sea",name:"Af Rusty Sea",cat:"i_arty"},
  {id:"af_rusty_thorn",name:"Af Rusty Thorn",cat:"i_arty"},
  {id:"wpn_ak101",name:"AK-101",cat:"w_rifle"},
  {id:"wpn_ak101_camo",name:"AK-101 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_ak102",name:"AK-102",cat:"w_rifle"},
  {id:"wpn_ak103",name:"AK-103",cat:"w_rifle"},
  {id:"wpn_ak103_camo",name:"AK-103 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_ak104",name:"AK-104",cat:"w_rifle"},
  {id:"wpn_ak105",name:"AK-105",cat:"w_rifle"},
  {id:"wpn_ak12",name:"AK-12",cat:"w_rifle"},
  {id:"wpn_ak",name:"AK-47",cat:"w_rifle"},
  {id:"wpn_ak74_old",name:"AK-74",cat:"w_rifle"},
  {id:"wpn_ak74m",name:"AK-74M",cat:"w_rifle"},
  {id:"wpn_ak74m_alt",name:"AK-74M (alternate)",cat:"w_rifle"},
  {id:"wpn_ak74m_camo",name:"AK-74M (camouflaged)",cat:"w_rifle"},
  {id:"wpn_ak74m_custom",name:"AK-74M (custom)",cat:"w_rifle"},
  {id:"wpn_ak74m_duty",name:"AK-74M (Duty camouflage)",cat:"w_rifle"},
  {id:"wpn_ak74m_pka",name:"AK-74M PK-A",cat:"w_rifle"},
  {id:"wpn_ak74",name:"AK-74N",cat:"w_rifle"},
  {id:"wpn_ak74_alt",name:"AK-74N (alternate)",cat:"w_rifle"},
  {id:"wpn_ak74_custom",name:"AK-74N (custom)",cat:"w_rifle"},
  {id:"wpn_ak74_modern",name:"AK-74N (modern)",cat:"w_rifle"},
  {id:"wpn_akm",name:"AKMN",cat:"w_rifle"},
  {id:"wpn_akms",name:"AKMSN",cat:"w_rifle"},
  {id:"wpn_akms_alt",name:"AKMSN (alternate)",cat:"w_rifle"},
  {id:"wpn_aks",name:"AKS-47",cat:"w_rifle"},
  {id:"wpn_aks74",name:"AKS-74N",cat:"w_rifle"},
  {id:"wpn_aks74_new",name:"AKS-74N (new)",cat:"w_rifle"},
  {id:"wpn_ak74u_old",name:"AKS-74U",cat:"w_rifle"},
  {id:"wpn_ak74u",name:"AKS-74UN",cat:"w_rifle"},
  {id:"wpn_ak74u_camo",name:"AKS-74UN (camouflaged)",cat:"w_rifle"},
  {id:"wpn_ak74u_custom",name:"AKS-74UN (custom)",cat:"w_rifle"},
  {id:"wpn_ak74u_snag",name:"AKS-74UNB (customised)",cat:"w_rifle"},
  {id:"af_frames",name:"Aluminium frames",cat:"i_arty"},
  {id:"prt_o_retardant_12",name:"Aluminized fiberglass fabrics",cat:"i_part"},
  {id:"prt_o_retardant_11",name:"Aluminized layers of retardant fabrics",cat:"i_part"},
  {id:"ammo_12x76_dart_bad",name:"Ammo 12x76 Dart Bad",cat:"w_ammo"},
  {id:"ammo_12x76_dart_verybad",name:"Ammo 12x76 Dart Verybad",cat:"w_ammo"},
  {id:"ammo_binoc",name:"Ammo Binoc",cat:"w_ammo"},
  {id:"ammo_dyno",name:"Ammo Dyno",cat:"w_ammo"},
  {id:"ammo_knife",name:"Ammo Knife",cat:"w_ammo"},
  {id:"ammo_knife_2",name:"Ammo Knife 2",cat:"w_ammo"},
  {id:"ammo_knife_3",name:"Ammo Knife 3",cat:"w_ammo"},
  {id:"ammo_knife_4",name:"Ammo Knife 4",cat:"w_ammo"},
  {id:"ammo_knife_5",name:"Ammo Knife 5",cat:"w_ammo"},
  {id:"prt_i_ammo",name:"Ammo parts",cat:"i_part"},
  {id:"wpn_abakan",name:"AN-94",cat:"w_rifle"},
  {id:"wpn_abakan_camo",name:"AN-94 (camouflaged)",cat:"w_rifle"},
  {id:"drug_anabiotic",name:"Anabiotics",cat:"i_medical"},
  {id:"af_misery_bread",name:"Anomalous bread",cat:"i_arty"},
  {id:"detector_anomaly",name:"Anomalous measurement device",cat:"i_device"},
  {id:"itm_mapkit_9",name:"Anomaly map (Agroprom)",cat:"i_kit"},
  {id:"itm_mapkit_1",name:"Anomaly map (Army Warehouses)",cat:"i_kit"},
  {id:"itm_mapkit_4",name:"Anomaly map (Dead City)",cat:"i_kit"},
  {id:"itm_mapkit_8",name:"Anomaly map (Garbage)",cat:"i_kit"},
  {id:"itm_mapkit_6",name:"Anomaly map (Jupiter)",cat:"i_kit"},
  {id:"itm_mapkit_3",name:"Anomaly map (Red Forest)",cat:"i_kit"},
  {id:"itm_mapkit_5",name:"Anomaly map (Truck Cemetery)",cat:"i_kit"},
  {id:"itm_mapkit_2",name:"Anomaly map (Yantar)",cat:"i_kit"},
  {id:"itm_mapkit_7",name:"Anomaly map (Zaton)",cat:"i_kit"},
  {id:"drug_antidot",name:"Antidote",cat:"i_medical"},
  {id:"helm_metro",name:"Apocalypse helm",cat:"o_helmet"},
  {id:"wpn_aps",name:"APS",cat:"w_pistol"},
  {id:"wpn_sil_aps",name:"APS suppressor",cat:"w_misc"},
  {id:"bandit_novice_outfit_alt",name:"Armoured leather jacket",cat:"o_medium"},
  {id:"wpn_protecta",name:"Armsel Protecta",cat:"w_shotgun"},
  {id:"wpn_protecta_camo",name:"Armsel Protecta (camouflaged)",cat:"w_shotgun"},
  {id:"wpn_protecta_nimble",name:"Armsel Protecta (custom)",cat:"w_shotgun"},
  {id:"wpn_protecta_custom",name:"Armsel Protecta (customised)",cat:"w_shotgun"},
  {id:"wpn_protecta_aim",name:"Armsel Protecta (modern)",cat:"w_shotgun"},
  {id:"army_bowler__2",name:"Army Bowler  2",cat:"i_food"},
  {id:"army_bowler__3",name:"Army Bowler  3",cat:"i_food"},
  {id:"medkit_ai2",name:"Army medical package",cat:"i_medical"},
  {id:"medkit_army",name:"Army medkit",cat:"i_medical"},
  {id:"af_aac",name:"Artefact Application Container (empty)",cat:"i_arty"},
  {id:"af_aam",name:"Artefact Application Module (empty)",cat:"i_arty"},
  {id:"wpn_val",name:"AS Val",cat:"w_rifle"},
  {id:"wpn_val_modern",name:"AS Val (modern)",cat:"w_rifle"},
  {id:"wpn_ash12",name:"ASh-12.7",cat:"w_rifle"},
  {id:"wpn_sil_atg",name:"ATG suppressor",cat:"w_misc"},
  {id:"af_atom",name:"Atom",cat:"i_arty"},
  {id:"wpn_axe",name:"Axe",cat:"w_melee"},
  {id:"itm_backpack",name:"Backpack",cat:"i_attach"},
  {id:"itm_tent",name:"Bag with a camping tent",cat:"i_misc"},
  {id:"helm_rp_bala",name:"Balaclava",cat:"o_helmet"},
  {id:"af_ball",name:"Ball",cat:"i_arty"},
  {id:"ball_hammer",name:"Ball-peen hammer",cat:"i_misc"},
  {id:"bandage",name:"Bandage",cat:"i_medical"},
  {id:"helm_bandana",name:"Bandana",cat:"o_helmet"},
  {id:"wpn_m82",name:"Barrett M82",cat:"w_rifle"},
  {id:"medkit_ai1",name:"Basic medical package",cat:"i_medical"},
  {id:"itm_basickit",name:"Basic tools",cat:"i_kit"},
  {id:"af_vaselisk",name:"Basilisk",cat:"i_arty"},
  {id:"af_bat",name:"Bat",cat:"i_arty"},
  {id:"ammo_gauss",name:"Batteries",cat:"w_ammo"},
  {id:"ammo_gauss_bad",name:"Batteries",cat:"w_ammo"},
  {id:"ammo_gauss_verybad",name:"Batteries",cat:"w_ammo"},
  {id:"af_dummy_battery",name:"Battery",cat:"i_arty"},
  {id:"batteries_dead",name:"Battery pack",cat:"i_misc"},
  {id:"af_lighthouse",name:"Beacon",cat:"i_arty"},
  {id:"detector_advanced",name:"Bear detector",cat:"i_device"},
  {id:"beadspread",name:"Bed spread",cat:"i_misc"},
  {id:"wpn_beretta",name:"Beretta 92F",cat:"w_pistol"},
  {id:"wpn_beretta_alt",name:"Beretta 92F (alternate)",cat:"w_pistol"},
  {id:"wpn_beretta_camo",name:"Beretta 92F (camouflaged)",cat:"w_pistol"},
  {id:"wpn_beretta_modern",name:"Beretta 92F (modern)",cat:"w_pistol"},
  {id:"specops_outfit",name:"Berill-5M armoured suit",cat:"o_medium"},
  {id:"af_black_angel",name:"Black Angel",cat:"i_arty"},
  {id:"bandit_novice_outfit",name:"Black leather jacket",cat:"o_medium"},
  {id:"af_black_spray",name:"Black Spray",cat:"i_arty"},
  {id:"af_black",name:"Black Stone",cat:"i_arty"},
  {id:"mutant_part_heart_bloodsucker",name:"Bloodsucker heart",cat:"i_mutant_part"},
  {id:"mutant_part_krovosos_jaw",name:"Bloodsucker jaw",cat:"i_mutant_part"},
  {id:"mutant_part_krovosos_meat",name:"Bloodsucker meat",cat:"i_mutant_part"},
  {id:"mutant_part_boar_chop",name:"Boar chop",cat:"i_mutant_part"},
  {id:"mutant_part_tusk_boar",name:"Boar fang",cat:"i_mutant_part"},
  {id:"mutant_part_boar_leg",name:"Boar leg",cat:"i_mutant_part"},
  {id:"af_cooler",name:"Body cooler",cat:"i_arty"},
  {id:"af_bracelet",name:"Bracelet",cat:"i_arty"},
  {id:"bread",name:"Bread loaf",cat:"i_food"},
  {id:"breadold",name:"Breadcrumbs",cat:"i_food"},
  {id:"broken_detector",name:"Broken detector",cat:"i_misc"},
  {id:"flashlight_broken",name:"Broken flashlight",cat:"i_misc"},
  {id:"radio2",name:"Broken radio",cat:"i_misc"},
  {id:"wpn_hpsa",name:"Browning Hi-Power",cat:"w_pistol"},
  {id:"wpn_hpsa_alt",name:"Browning Hi-Power (alternate)",cat:"w_pistol"},
  {id:"af_baloon",name:"Bubble",cat:"i_arty"},
  {id:"mutant_part_brain_burer",name:"Burer brain",cat:"i_mutant_part"},
  {id:"mutant_part_burer_hand",name:"Burer hand",cat:"i_mutant_part"},
  {id:"caffeine__1",name:"Caffeine  1",cat:"i_medical"},
  {id:"caffeine__2",name:"Caffeine  2",cat:"i_medical"},
  {id:"caffeine__3",name:"Caffeine  3",cat:"i_medical"},
  {id:"caffeine__4",name:"Caffeine  4",cat:"i_medical"},
  {id:"caffeine__5",name:"Caffeine  5",cat:"i_medical"},
  {id:"af_camelbak",name:"Camelbak",cat:"i_arty"},
  {id:"tarpaulin",name:"Camouflaged tarpaulin",cat:"i_misc"},
  {id:"equ_small_pack",name:"Camping backpack",cat:"i_misc"},
  {id:"tomato",name:"Canned tomatoes",cat:"i_misc"},
  {id:"prt_o_ballistic_19",name:"Carbon fibre layers",cat:"i_part"},
  {id:"prt_o_ballistic_16",name:"Carbon nanotube layers w/ Kevlar-29 fabrics (Reinforced)",cat:"i_part"},
  {id:"prt_o_ballistic_15",name:"Carbon nanotube layers w/ Kevlar-49 fabrics",cat:"i_part"},
  {id:"af_plates",name:"Carbon steel plates",cat:"i_arty"},
  {id:"mutant_part_cat_claw",name:"Cat claw",cat:"i_mutant_part"},
  {id:"mutant_part_cat_tail",name:"Cat tail",cat:"i_mutant_part"},
  {id:"mutant_part_cat_thyroid",name:"Cat thyroid",cat:"i_mutant_part"},
  {id:"af_cell",name:"Cell",cat:"i_arty"},
  {id:"prt_i_ceramic",name:"Ceramic base",cat:"i_part"},
  {id:"wpn_pm_actor",name:"Ceremonial Makarov PM",cat:"w_pistol"},
  {id:"af_chelust",name:"Chain",cat:"i_arty"},
  {id:"freedom_nosorog_outfit",name:"Champion of Freedom",cat:"o_heavy"},
  {id:"charcoal__1",name:"Charcoal  1",cat:"i_misc"},
  {id:"charcoal__2",name:"Charcoal  2",cat:"i_misc"},
  {id:"monolith_nbc_outfit",name:"Chernobyl NBC suit",cat:"o_medium"},
  {id:"mutant_part_chimera_claw",name:"Chimera claw",cat:"i_mutant_part"},
  {id:"mutant_part_heart_chimera",name:"Chimera heart",cat:"i_mutant_part"},
  {id:"mutant_part_chimera_kogot",name:"Chimera horn",cat:"i_mutant_part"},
  {id:"prt_w_bolt_carrier_9",name:"Chock from a double-barrel shotgun [R]",cat:"i_part"},
  {id:"prt_w_bolt_carrier_8",name:"Chock from double-barrel shotgun [R]",cat:"i_part"},
  {id:"protein",name:"Chocolate protein bar",cat:"i_food"},
  {id:"mutant_part_chimera_meat",name:"Chunk of chimera meat",cat:"i_mutant_part"},
  {id:"cigar1__1",name:"Cigar1  1",cat:"i_misc"},
  {id:"cigar1__2",name:"Cigar1  2",cat:"i_misc"},
  {id:"cigar1__3",name:"Cigar1  3",cat:"i_misc"},
  {id:"cigar2__1",name:"Cigar2  1",cat:"i_misc"},
  {id:"cigar2__2",name:"Cigar2  2",cat:"i_misc"},
  {id:"cigar2__3",name:"Cigar2  3",cat:"i_misc"},
  {id:"cigar3__1",name:"Cigar3  1",cat:"i_misc"},
  {id:"cigar3__2",name:"Cigar3  2",cat:"i_misc"},
  {id:"cigar3__3",name:"Cigar3  3",cat:"i_misc"},
  {id:"cigarettes__1",name:"Cigarettes  1",cat:"i_food"},
  {id:"cigarettes__2",name:"Cigarettes  2",cat:"i_food"},
  {id:"cigarettes__3",name:"Cigarettes  3",cat:"i_food"},
  {id:"cigarettes_lucky__1",name:"Cigarettes Lucky  1",cat:"i_food"},
  {id:"cigarettes_lucky__2",name:"Cigarettes Lucky  2",cat:"i_food"},
  {id:"cigarettes_lucky__3",name:"Cigarettes Lucky  3",cat:"i_food"},
  {id:"cigarettes_russian__1",name:"Cigarettes Russian  1",cat:"i_food"},
  {id:"cigarettes_russian__2",name:"Cigarettes Russian  2",cat:"i_food"},
  {id:"cigarettes_russian__3",name:"Cigarettes Russian  3",cat:"i_food"},
  {id:"af_kogot",name:"Claw",cat:"i_arty"},
  {id:"cs_novice_outfit",name:"Clear Sky leather jacket",cat:"o_medium"},
  {id:"helm_cloth_mask",name:"Cloth mask",cat:"o_helmet"},
  {id:"prt_o_fabrics_1",name:"Cloth sheets",cat:"i_part"},
  {id:"prt_o_fabrics_2",name:"Cloth sheets (synthetic)",cat:"i_part"},
  {id:"af_cocoon",name:"Cocoon",cat:"i_arty"},
  {id:"wpn_colt1911",name:"Colt M1911",cat:"w_pistol"},
  {id:"wpn_colt1911_alt",name:"Colt M1911 (alternate)",cat:"w_pistol"},
  {id:"wpn_colt1911_camo",name:"Colt M1911 (camouflaged)",cat:"w_pistol"},
  {id:"wpn_colt1911_custom",name:"Colt M1911 (custom)",cat:"w_pistol"},
  {id:"wpn_colt1911_duty",name:"Colt M1911 (Duty camouflage)",cat:"w_pistol"},
  {id:"wpn_colt1911_merc",name:"Colt M1911 (merc camouflage)",cat:"w_pistol"},
  {id:"wpn_colt1911_modern",name:"Colt M1911 (modern)",cat:"w_pistol"},
  {id:"wpn_colt1911_new",name:"Colt M1911 (new)",cat:"w_pistol"},
  {id:"equ_military_pack",name:"Combat backpack",cat:"i_misc"},
  {id:"af_compass",name:"Compass",cat:"i_arty"},
  {id:"mutant_part_controller_glass",name:"Controller brain tissue",cat:"i_mutant_part"},
  {id:"mutant_part_controller_hand",name:"Controller hand",cat:"i_mutant_part"},
  {id:"cooking__1",name:"Cooking  1",cat:"i_misc"},
  {id:"cooking__2",name:"Cooking  2",cat:"i_misc"},
  {id:"prt_i_copper",name:"Copper wire",cat:"i_part"},
  {id:"af_cristall",name:"Crystal",cat:"i_arty"},
  {id:"cs_light_novice_outfit",name:"CS-1 body armour",cat:"o_medium"},
  {id:"cs_light_outfit",name:"CS-2a body armour",cat:"o_medium"},
  {id:"cs_stalker_outfit",name:"CS-2b body armour",cat:"o_medium"},
  {id:"cs_stalker_proto_exo_outfit",name:"CS-2b proto-exoskeleton",cat:"o_heavy"},
  {id:"cs_nbc_outfit",name:"CS-3 NBC body armour",cat:"o_medium"},
  {id:"cs_medium_outfit",name:"CS-3a body armour",cat:"o_medium"},
  {id:"cs_heavy_outfit",name:"CS-3b body armour",cat:"o_heavy"},
  {id:"cs_scientific_outfit_good",name:"CS-4a pathfinder",cat:"o_medium"},
  {id:"cs_scientific_outfit",name:"CS-4a SEVA suit",cat:"o_medium"},
  {id:"military_sky_outfit",name:"CS-4b armoured suit",cat:"o_medium"},
  {id:"cs_exo_outfit",name:"CS-5 exoskeleton",cat:"o_heavy"},
  {id:"cs_exolight_outfit",name:"CS-5 exosuit",cat:"o_heavy"},
  {id:"cigar",name:"Cuban cigar",cat:"i_misc"},
  {id:"wpn_cz52",name:"CZ 52",cat:"w_pistol"},
  {id:"wpn_cz75",name:"CZ-75",cat:"w_pistol"},
  {id:"wpn_cz75_auto",name:"CZ-75 Automatic",cat:"w_pistol"},
  {id:"helm_spartan",name:"Cz-M10 Spartan helmet",cat:"o_helmet"},
  {id:"af_death_lamp",name:"Death Lamp",cat:"i_arty"},
  {id:"cards",name:"Deck of cards",cat:"i_misc"},
  {id:"jewelry_box",name:"Decorated jewellery box",cat:"i_misc"},
  {id:"light_freedom_outfit",name:"Defender of Freedom",cat:"o_medium"},
  {id:"wpn_desert_eagle",name:"Desert Eagle",cat:"w_pistol"},
  {id:"wpn_desert_eagle_custom",name:"Desert Eagle (custom)",cat:"w_pistol"},
  {id:"wpn_desert_eagle_modern",name:"Desert Eagle (modern)",cat:"w_pistol"},
  {id:"specops_bandit_outfit",name:"Deserter's B-5M armoured suit",cat:"o_medium"},
  {id:"device_flare",name:"Device Flare",cat:"i_device"},
  {id:"device_flash_snag",name:"Device Flash Snag",cat:"i_device"},
  {id:"device_pda_port_bandit_leader",name:"Device Pda Port Bandit Leader",cat:"i_device"},
  {id:"device_pda_zat_b5_dealer",name:"Device Pda Zat B5 Dealer",cat:"i_device"},
  {id:"mutant_part_dog_heart",name:"Dog heart",cat:"i_mutant_part"},
  {id:"mutant_part_dog_liver",name:"Dog liver",cat:"i_mutant_part"},
  {id:"mutant_part_dog_meat",name:"Dog meat",cat:"i_mutant_part"},
  {id:"mutant_part_dog_tail",name:"Dog tail",cat:"i_mutant_part"},
  {id:"device_weather_radar",name:"Doppler weather radar kit",cat:"i_device"},
  {id:"prt_w_trigger_components_5",name:"Double fire mode trigger mechanism with firing pin",cat:"i_part"},
  {id:"prt_w_trigger_components_2",name:"Double fire mode trigger mechanism with hammer",cat:"i_part"},
  {id:"prt_w_p_trigger_3",name:"Double-action (DA/SA) trigger mechanism",cat:"i_part"},
  {id:"prt_w_p_trigger_2",name:"Double-action trigger mechanism",cat:"i_part"},
  {id:"af_dragon_eye",name:"Dragon's eye",cat:"i_arty"},
  {id:"prt_w_bolt_1",name:"Dropping-block breech [R]",cat:"i_part"},
  {id:"drug_sleepingpills__2",name:"Drug Sleepingpills  2",cat:"i_medical"},
  {id:"drug_sleepingpills__3",name:"Drug Sleepingpills  3",cat:"i_medical"},
  {id:"itm_drugkit",name:"Drug-making kit",cat:"i_kit"},
  {id:"prt_w_bolt_15",name:"Drummer with the mainspring [PP]",cat:"i_part"},
  {id:"prt_w_bolt_16",name:"Drummer with the mainspring [PP][NATO]",cat:"i_part"},
  {id:"prt_w_bolt_17",name:"Drummer with the mainspring [PP][PPSh]",cat:"i_part"},
  {id:"duct_tape",name:"Duct tape",cat:"i_misc"},
  {id:"prt_o_fabrics_3",name:"Durable textiles",cat:"i_part"},
  {id:"dolg_novice_outfit",name:"Duty leather jacket",cat:"o_medium"},
  {id:"detector_simple",name:"Echo detector",cat:"i_device"},
  {id:"ecolog_proto_exo_outfit",name:"Ecologist guard proto-exoskeleton",cat:"o_heavy"},
  {id:"prt_w_gas_tube_8",name:"Ejector [V]",cat:"i_part"},
  {id:"prt_w_gas_tube_10",name:"Ejector from an over-under double barrel shotgun [R]",cat:"i_part"},
  {id:"prt_w_gas_tube_9",name:"Ejector from over-under double-barrel shotgun [R]",cat:"i_part"},
  {id:"af_elektron",name:"Electron",cat:"i_arty"},
  {id:"af_empty",name:"Empty",cat:"i_arty"},
  {id:"itm_tent_bag",name:"Empty bag for camping tent",cat:"i_misc"},
  {id:"e_syringe",name:"Empty syringe",cat:"i_misc"},
  {id:"helm_exo",name:"Exohelm",cat:"o_helmet"},
  {id:"exo_outfit",name:"Exoskeleton",cat:"o_heavy"},
  {id:"prt_o_support_1",name:"Exoskeleton frame",cat:"i_part"},
  {id:"exolight_outfit",name:"Exosuit",cat:"o_heavy"},
  {id:"itm_expertkit",name:"Expert tools",cat:"i_kit"},
  {id:"af_eye",name:"Eye",cat:"i_arty"},
  {id:"grenade_f1",name:"F1 grenade",cat:"w_explosive"},
  {id:"prt_i_fasteners",name:"Fasteners",cat:"i_part"},
  {id:"banditmerc_outfit",name:"Fenced LC suit",cat:"o_medium"},
  {id:"bandit_ps5_outfit",name:"Fenced PS5-M universal protection",cat:"o_medium"},
  {id:"cutlery",name:"Field cutlery",cat:"i_misc"},
  {id:"wpn_axe2",name:"Fire axe",cat:"w_melee"},
  {id:"novice_outfit_camo",name:"Firearm enthusiast's jacket",cat:"o_medium"},
  {id:"af_fireball",name:"Fireball",cat:"i_arty"},
  {id:"af_glass",name:"Firefly",cat:"i_arty"},
  {id:"matches",name:"Firestarter set",cat:"i_misc"},
  {id:"medkit",name:"First-aid kit",cat:"i_medical"},
  {id:"medkit_script",name:"First-aid kit",cat:"i_medical"},
  {id:"af_fire",name:"Flame",cat:"i_arty"},
  {id:"af_electra_flash",name:"Flash",cat:"i_arty"},
  {id:"device_flashlight",name:"Flashlight",cat:"i_device"},
  {id:"mutant_part_flesh_eye",name:"Flesh eye",cat:"i_mutant_part"},
  {id:"mutant_part_flesh_meat",name:"Flesh meat",cat:"i_mutant_part"},
  {id:"wpn_fn2000",name:"FN F2000",cat:"w_rifle"},
  {id:"wpn_fn2000_camo",name:"FN F2000 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_fn2000_custom",name:"FN F2000 (customised)",cat:"w_rifle"},
  {id:"wpn_fn2000_nimble",name:"FN F2000 EOTech",cat:"w_rifle"},
  {id:"wpn_fal",name:"FN FAL",cat:"w_rifle"},
  {id:"wpn_fn57",name:"FN Five-seveN",cat:"w_rifle"},
  {id:"wpn_fnc",name:"FN FNC",cat:"w_rifle"},
  {id:"wpn_p90",name:"FN P90",cat:"w_smg"},
  {id:"wpn_scar",name:"FN SCAR-H",cat:"w_rifle"},
  {id:"wpn_scar_custom",name:"FN SCAR-H (camouflaged)",cat:"w_rifle"},
  {id:"wpn_scar_new",name:"FN SCAR-H (new)",cat:"w_rifle"},
  {id:"wpn_fnp45",name:"FNP-45",cat:"w_rifle"},
  {id:"wpn_fnp45_custom",name:"FNP-45 (custom)",cat:"w_rifle"},
  {id:"wpn_fnx45",name:"FNX-45 Tactical",cat:"w_rifle"},
  {id:"wpn_fnx45_alt",name:"FNX-45 Tactical (alternate)",cat:"w_rifle"},
  {id:"wpn_fnx45_custom",name:"FNX-45 Tactical (custom)",cat:"w_rifle"},
  {id:"wpn_fort",name:"Fort-17",cat:"w_pistol"},
  {id:"wpn_fort500",name:"Fort-500",cat:"w_pistol"},
  {id:"af_fountain",name:"Fountain",cat:"i_arty"},
  {id:"mutant_part_fracture_hand",name:"Fracture hand",cat:"i_mutant_part"},
  {id:"svoboda_novice_outfit",name:"Freedom leather jacket",cat:"o_medium"},
  {id:"svoboda_light_proto_exo_outfit",name:"Freedom proto-exoskeleton",cat:"o_heavy"},
  {id:"af_freon",name:"Freon emission module",cat:"i_arty"},
  {id:"af_full_empty",name:"Full Empty",cat:"i_arty"},
  {id:"wpn_g36",name:"G36",cat:"w_rifle"},
  {id:"wpn_g36_camo",name:"G36 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_g36k",name:"G36K",cat:"w_rifle"},
  {id:"wpn_g3",name:"G3A3",cat:"w_rifle"},
  {id:"wpn_g3sg1",name:"G3SG1",cat:"w_rifle"},
  {id:"wpn_addon_scope_galil",name:"Galil 4.0x scope",cat:"w_misc"},
  {id:"wpn_ace21",name:"Galil ACE-21",cat:"w_rifle"},
  {id:"wpn_galil",name:"Galil AR",cat:"w_rifle"},
  {id:"wpn_galil_custom",name:"Galil AR (custom)",cat:"w_rifle"},
  {id:"wpn_galil_modern",name:"Galil AR (modern)",cat:"w_rifle"},
  {id:"prt_w_gas_tube_4",name:"Gas tube [AS/PP]",cat:"i_part"},
  {id:"prt_w_gas_tube_6",name:"Gas tube [A|V][NATO]",cat:"i_part"},
  {id:"prt_w_gas_tube_5",name:"Gas tube [A|V][Russia]",cat:"i_part"},
  {id:"prt_w_gas_tube_1",name:"Gas tube [K]",cat:"i_part"},
  {id:"prt_w_gas_tube_7",name:"Gas tube [P]",cat:"i_part"},
  {id:"prt_w_gas_tube_11",name:"Gas tube [PP]",cat:"i_part"},
  {id:"prt_w_gas_tube_3",name:"Gas tube [V]",cat:"i_part"},
  {id:"wpn_gauss",name:"Gauss rifle",cat:"w_sniper"},
  {id:"detector_geiger",name:"Geiger counter",cat:"i_device"},
  {id:"wpn_sil_gemtech",name:"Gemtech suppressor",cat:"w_misc"},
  {id:"af_generator",name:"Generator",cat:"i_arty"},
  {id:"ghillie_outfit",name:"Ghillie suit",cat:"o_medium"},
  {id:"af_gimlet",name:"Gimlet",cat:"i_arty"},
  {id:"prt_i_glass",name:"Glass pieces",cat:"i_part"},
  {id:"wpn_glock",name:"Glock 19",cat:"w_pistol"},
  {id:"wpn_glock_modern",name:"Glock 19 (alternate)",cat:"w_pistol"},
  {id:"wpn_glock_custom",name:"Glock 19 (custom)",cat:"w_pistol"},
  {id:"af_gold_fish",name:"Goldfish",cat:"i_arty"},
  {id:"helm_ranger",name:"GP-10z ranger gas mask",cat:"o_helmet"},
  {id:"helm_respirator_gp5",name:"GP-5 gas mask",cat:"o_helmet"},
  {id:"prt_o_ballistic_10",name:"Grade-A polyethylene plates w/ expanded carrier",cat:"i_part"},
  {id:"prt_o_retardant_4",name:"Grade-A RPVC vinyl fabrics",cat:"i_part"},
  {id:"prt_o_ballistic_9",name:"Grade-B polyethylene plates w/ expanded carrier",cat:"i_part"},
  {id:"prt_o_retardant_3",name:"Grade-B RPVC treated fabrics",cat:"i_part"},
  {id:"af_grapes",name:"Grapes",cat:"i_arty"},
  {id:"af_gravi",name:"Gravi",cat:"i_arty"},
  {id:"grooming",name:"Grooming kit",cat:"i_misc"},
  {id:"wpn_gsh18",name:"Gsh-18",cat:"w_rifle"},
  {id:"wpn_gsh18_custom",name:"Gsh-18 (custom)",cat:"w_rifle"},
  {id:"svoboda_heavy_outfit",name:"Guardian of Freedom",cat:"o_heavy"},
  {id:"itm_gunsmith_toolkit",name:"Gunsmith kit",cat:"i_kit"},
  {id:"itm_ammokit",name:"Gunsmithing tools",cat:"i_kit"},
  {id:"prt_w_bolt_carrier_5",name:"Half-free sliding bolt carrier",cat:"i_part"},
  {id:"prt_w_bolt_12",name:"Hammers from a hammer-type double-barrel shotgun [R]",cat:"i_part"},
  {id:"hand_rolling_tobacco__1",name:"Hand Rolling Tobacco  1",cat:"i_misc"},
  {id:"hand_rolling_tobacco__2",name:"Hand Rolling Tobacco  2",cat:"i_misc"},
  {id:"hand_rolling_tobacco__3",name:"Hand Rolling Tobacco  3",cat:"i_misc"},
  {id:"hand_watch",name:"Hand watch",cat:"i_misc"},
  {id:"prt_w_gas_tube_2",name:"Handguard [R]",cat:"i_part"},
  {id:"harmonica_a",name:"Harmonica",cat:"i_misc"},
  {id:"device_torch",name:"Headlamp",cat:"i_device"},
  {id:"device_torch_dummy",name:"Headlamp",cat:"i_device"},
  {id:"device_torch_nv_1",name:"Headlamp w/ 1PN93-1 Nightvision\\n",cat:"i_device"},
  {id:"device_torch_nv_3",name:"Headlamp w/ Oracle psy-stimulator",cat:"i_device"},
  {id:"device_torch_nv_2",name:"Headlamp w/ PN21KL Nightvision\\n",cat:"i_device"},
  {id:"af_ear",name:"Heart",cat:"i_arty"},
  {id:"af_oasis_heart",name:"Heart of the Oasis",cat:"i_arty"},
  {id:"trenchcoat_brown_outfit",name:"Heavy brown overcoat",cat:"o_medium"},
  {id:"trenchcoat_dolg_brown_outfit",name:"Heavy Duty overcoat",cat:"o_medium"},
  {id:"trenchcoat_freedom_brown_outfit",name:"Heavy Freedom overcoat",cat:"o_medium"},
  {id:"trenchcoat_green_outfit",name:"Heavy green overcoat",cat:"o_medium"},
  {id:"bandit_exo_outfit",name:"Heisted exoskeleton",cat:"o_heavy"},
  {id:"af_geliy",name:"Helium",cat:"i_arty"},
  {id:"drug_booster",name:"Hercules",cat:"i_medical"},
  {id:"freedom_exo_vineleaf_outfit",name:"Hero of Freedom",cat:"o_heavy"},
  {id:"wpn_hk416",name:"HK416",cat:"w_rifle"},
  {id:"wpn_hk417",name:"HK417",cat:"w_rifle"},
  {id:"ammo_12x70_buck_self",name:"Home-made 12x70 shot shells",cat:"w_ammo"},
  {id:"ammo_gauss_cardan",name:"Home-made batteries",cat:"w_ammo"},
  {id:"wpn_axe3",name:"Hunting axe",cat:"w_melee"},
  {id:"wpn_knife3",name:"Hunting knife",cat:"w_melee"},
  {id:"hybrid_outfit",name:"Hybrid armoured suit",cat:"o_medium"},
  {id:"af_misery_bread_af_iam",name:"IAM w/ anomalous bread",cat:"i_arty"},
  {id:"af_dummy_battery_af_iam",name:"IAM w/ Battery",cat:"i_arty"},
  {id:"af_black_spray_af_iam",name:"IAM w/ Black Spray",cat:"i_arty"},
  {id:"af_bracelet_af_iam",name:"IAM w/ Bracelet",cat:"i_arty"},
  {id:"af_baloon_af_iam",name:"IAM w/ Bubble",cat:"i_arty"},
  {id:"af_compass_af_iam",name:"IAM w/ Compass",cat:"i_arty"},
  {id:"af_cristall_af_iam",name:"IAM w/ Crystal",cat:"i_arty"},
  {id:"af_death_lamp_af_iam",name:"IAM w/ Death Lamp",cat:"i_arty"},
  {id:"af_empty_af_iam",name:"IAM w/ Empty",cat:"i_arty"},
  {id:"af_eye_af_iam",name:"IAM w/ Eye",cat:"i_arty"},
  {id:"af_fireball_af_iam",name:"IAM w/ Fireball",cat:"i_arty"},
  {id:"af_glass_af_iam",name:"IAM w/ Firefly",cat:"i_arty"},
  {id:"af_fire_af_iam",name:"IAM w/ Flame",cat:"i_arty"},
  {id:"af_electra_flash_af_iam",name:"IAM w/ Flash",cat:"i_arty"},
  {id:"af_full_empty_af_iam",name:"IAM w/ Full Empty",cat:"i_arty"},
  {id:"af_gold_fish_af_iam",name:"IAM w/ Goldfish",cat:"i_arty"},
  {id:"af_gravi_af_iam",name:"IAM w/ Gravi",cat:"i_arty"},
  {id:"af_oasis_heart_af_iam",name:"IAM w/ Heart of the Oasis",cat:"i_arty"},
  {id:"af_itcher_af_iam",name:"IAM w/ Itcher",cat:"i_arty"},
  {id:"af_medusa_af_iam",name:"IAM w/ Jellyfish",cat:"i_arty"},
  {id:"af_fuzz_kolobok_af_iam",name:"IAM w/ Kolobok",cat:"i_arty"},
  {id:"af_lobster_eyes_af_iam",name:"IAM w/ Lobster Eyes",cat:"i_arty"},
  {id:"af_dummy_glassbeads_af_iam",name:"IAM w/ Mama's Beads",cat:"i_arty"},
  {id:"af_mincer_meat_af_iam",name:"IAM w/ Meat Chunk",cat:"i_arty"},
  {id:"af_electra_moonlight_af_iam",name:"IAM w/ Moonlight",cat:"i_arty"},
  {id:"af_night_star_af_iam",name:"IAM w/ Nightstar",cat:"i_arty"},
  {id:"af_pin_af_iam",name:"IAM w/ Pin",cat:"i_arty"},
  {id:"af_ring_af_iam",name:"IAM w/ Ring",cat:"i_arty"},
  {id:"af_dummy_dummy_af_iam",name:"IAM w/ Shell",cat:"i_arty"},
  {id:"af_ice_af_iam",name:"IAM w/ Snowflake",cat:"i_arty"},
  {id:"af_soul_af_iam",name:"IAM w/ Soul",cat:"i_arty"},
  {id:"af_electra_sparkler_af_iam",name:"IAM w/ Sparkler",cat:"i_arty"},
  {id:"af_sponge_af_iam",name:"IAM w/ Sponge",cat:"i_arty"},
  {id:"af_blood_af_iam",name:"IAM w/ Stone Blood",cat:"i_arty"},
  {id:"af_cristall_flower_af_iam",name:"IAM w/ Stone Flower",cat:"i_arty"},
  {id:"af_vyvert_af_iam",name:"IAM w/ Wrenched",cat:"i_arty"},
  {id:"light_dolg_outfit",name:"IBAz universal protection",cat:"o_medium"},
  {id:"af_frames_up",name:"Improved aluminium frames",cat:"i_arty"},
  {id:"af_cooler_up",name:"Improved body cooler",cat:"i_arty"},
  {id:"af_camelbak_up",name:"Improved camelbak",cat:"i_arty"},
  {id:"af_plates_up",name:"Improved carbon steel plates",cat:"i_arty"},
  {id:"af_freon_up",name:"Improved freon emission module",cat:"i_arty"},
  {id:"af_kevlar_up",name:"Improved kevlar plates and attachments",cat:"i_arty"},
  {id:"af_surge_up",name:"Improved surge regenerator",cat:"i_arty"},
  {id:"af_grid_up",name:"Improved titanium grid",cat:"i_arty"},
  {id:"af_iam",name:"Improvised Application Module (empty)",cat:"i_arty"},
  {id:"ied",name:"Improvised explosive device (based on chemicals)",cat:"i_misc"},
  {id:"ied_blow",name:"Improvised explosive device (based on chemicals)",cat:"i_misc"},
  {id:"ied_new",name:"Improvised explosive device (based on chemicals)",cat:"i_misc"},
  {id:"ied_new_blow",name:"Improvised explosive device (based on chemicals)",cat:"i_misc"},
  {id:"ied_rpg",name:"Improvised explosive device (based on OG-7V warhead)",cat:"i_misc"},
  {id:"ied_rpg_new",name:"Improvised explosive device (based on OG-7V warhead)",cat:"i_misc"},
  {id:"grease",name:"Industrial grease",cat:"i_misc"},
  {id:"prt_o_retardant_17",name:"Insulating constantan inserts",cat:"i_part"},
  {id:"prt_o_retardant_18",name:"Insulating constantan inserts w/ fiberglass coating",cat:"i_part"},
  {id:"prt_o_retardant_7",name:"Insulating magnesium grid and inserts",cat:"i_part"},
  {id:"prt_o_retardant_8",name:"Insulating reinforced magnesium-oxide grid",cat:"i_part"},
  {id:"light_loner_outfit",name:"Interceptor body armour",cat:"o_medium"},
  {id:"greh_armored_outfit",name:"Irij flak armour",cat:"o_medium"},
  {id:"ecolog_guard_outfit",name:"ISRIT guard jumpsuit",cat:"o_sci"},
  {id:"af_itcher",name:"Itcher",cat:"i_arty"},
  {id:"itm_deployable_mgun",name:"Itm Deployable Mgun",cat:"i_misc"},
  {id:"itm_guide_usb_1",name:"Itm Guide Usb 1",cat:"i_misc"},
  {id:"itm_guide_usb_2",name:"Itm Guide Usb 2",cat:"i_misc"},
  {id:"itm_pda_personal",name:"Itm Pda Personal",cat:"i_misc"},
  {id:"af_medusa",name:"Jellyfish",cat:"i_arty"},
  {id:"wpn_g43",name:"Karabiner 43",cat:"w_rifle"},
  {id:"wpn_k98",name:"Karabiner 98 Kurz",cat:"w_rifle"},
  {id:"nbc_freedom_outfit",name:"Keeper of Freedom",cat:"o_medium"},
  {id:"kerosene__1",name:"Kerosene  1",cat:"i_misc"},
  {id:"kerosene__2",name:"Kerosene  2",cat:"i_misc"},
  {id:"prt_o_ballistic_5",name:"Kevlar AP and steel plates",cat:"i_part"},
  {id:"prt_o_ballistic_6",name:"Kevlar AP plates w/ reinforced titanium composite",cat:"i_part"},
  {id:"prt_o_ballistic_11",name:"Kevlar K119 plates",cat:"i_part"},
  {id:"prt_o_ballistic_8",name:"Kevlar K119 plates w/ carbon-fibre inserts",cat:"i_part"},
  {id:"prt_o_ballistic_7",name:"Kevlar K119 plates w/ Polycarbonate inserts",cat:"i_part"},
  {id:"prt_o_ballistic_4",name:"Kevlar K129 plates w/ carbon fibre composite",cat:"i_part"},
  {id:"prt_o_ballistic_3",name:"Kevlar K129 plates w/ Polycarbonate composite",cat:"i_part"},
  {id:"prt_o_ballistic_1",name:"Kevlar k129 plates w/ reinforced ceramic inserts",cat:"i_part"},
  {id:"af_kevlar",name:"Kevlar plates and attachments",cat:"i_arty"},
  {id:"prt_o_ballistic_2",name:"Kevlar Protera plates w/ reinforced ceramic inserts",cat:"i_part"},
  {id:"wpn_colt_kimber",name:"Kimber Desert Warrior",cat:"w_pistol"},
  {id:"af_fire_loop",name:"Knot",cat:"i_arty"},
  {id:"af_fuzz_kolobok",name:"Kolobok",cat:"i_arty"},
  {id:"wpn_sil_kzrzp",name:"KZRZP suppressor",cat:"w_misc"},
  {id:"wpn_l85",name:"L85A1",cat:"w_rifle"},
  {id:"wpn_l85_alt",name:"L85A1 (alternate)",cat:"w_rifle"},
  {id:"wpn_l85_custom",name:"L85A1 (custom)",cat:"w_rifle"},
  {id:"wpn_l85_modern",name:"L85A1 (modern)",cat:"w_rifle"},
  {id:"wpn_l85a2",name:"L85A2",cat:"w_rifle"},
  {id:"wpn_l85a2_alt",name:"L85A2 (alternate)",cat:"w_rifle"},
  {id:"wpn_l85a2_custom",name:"L85A2 (custom)",cat:"w_rifle"},
  {id:"wpn_l85a2_modern",name:"L85A2 (modern)",cat:"w_rifle"},
  {id:"wpn_l96a1m",name:"L96 AWSM",cat:"w_sniper"},
  {id:"wpn_l96a1",name:"L96A1",cat:"w_sniper"},
  {id:"af_fonar",name:"Lamp",cat:"i_arty"},
  {id:"glucose",name:"Large glucose shot",cat:"i_misc"},
  {id:"prt_o_retardant_2",name:"Layered chemical/shock retardant fabrics",cat:"i_part"},
  {id:"prt_o_retardant_1",name:"Layered fire retardant fabrics",cat:"i_part"},
  {id:"lead_box",name:"Lead-lined metal container (empty)",cat:"i_misc"},
  {id:"boots",name:"Leather boots",cat:"i_misc"},
  {id:"gloves",name:"Leather gloves",cat:"i_misc"},
  {id:"novice_outfit",name:"Leather jacket",cat:"o_medium"},
  {id:"prt_i_leather",name:"Leather roll",cat:"i_part"},
  {id:"prt_w_bolt_carrier_7",name:"Lever type bolt carrier with locking wedge",cat:"i_part"},
  {id:"military_freedom_outfit",name:"Liberated Skat-9 armoured suit",cat:"o_medium"},
  {id:"af_misery_bread_lead_box",name:"LLMC w/ anomalous bread",cat:"i_arty"},
  {id:"af_dummy_battery_lead_box",name:"LLMC w/ Battery",cat:"i_arty"},
  {id:"af_black_spray_lead_box",name:"LLMC w/ Black Spray",cat:"i_arty"},
  {id:"af_bracelet_lead_box",name:"LLMC w/ Bracelet",cat:"i_arty"},
  {id:"af_baloon_lead_box",name:"LLMC w/ Bubble",cat:"i_arty"},
  {id:"af_compass_lead_box",name:"LLMC w/ Compass",cat:"i_arty"},
  {id:"af_cristall_lead_box",name:"LLMC w/ Crystal",cat:"i_arty"},
  {id:"af_death_lamp_lead_box",name:"LLMC w/ Death Lamp",cat:"i_arty"},
  {id:"af_empty_lead_box",name:"LLMC w/ Empty",cat:"i_arty"},
  {id:"af_eye_lead_box",name:"LLMC w/ Eye",cat:"i_arty"},
  {id:"af_fireball_lead_box",name:"LLMC w/ Fireball",cat:"i_arty"},
  {id:"af_glass_lead_box",name:"LLMC w/ Firefly",cat:"i_arty"},
  {id:"af_fire_lead_box",name:"LLMC w/ Flame",cat:"i_arty"},
  {id:"af_electra_flash_lead_box",name:"LLMC w/ Flash",cat:"i_arty"},
  {id:"af_full_empty_lead_box",name:"LLMC w/ Full Empty",cat:"i_arty"},
  {id:"af_gold_fish_lead_box",name:"LLMC w/ Goldfish",cat:"i_arty"},
  {id:"af_gravi_lead_box",name:"LLMC w/ Gravi",cat:"i_arty"},
  {id:"af_oasis_heart_lead_box",name:"LLMC w/ Heart of the Oasis",cat:"i_arty"},
  {id:"af_itcher_lead_box",name:"LLMC w/ Itcher",cat:"i_arty"},
  {id:"af_medusa_lead_box",name:"LLMC w/ Jellyfish",cat:"i_arty"},
  {id:"af_fuzz_kolobok_lead_box",name:"LLMC w/ Kolobok",cat:"i_arty"},
  {id:"af_lobster_eyes_lead_box",name:"LLMC w/ Lobster Eyes",cat:"i_arty"},
  {id:"af_dummy_glassbeads_lead_box",name:"LLMC w/ Mama's Beads",cat:"i_arty"},
  {id:"af_mincer_meat_lead_box",name:"LLMC w/ Meat Chunk",cat:"i_arty"},
  {id:"af_electra_moonlight_lead_box",name:"LLMC w/ Moonlight",cat:"i_arty"},
  {id:"af_night_star_lead_box",name:"LLMC w/ Nightstar",cat:"i_arty"},
  {id:"af_pin_lead_box",name:"LLMC w/ Pin",cat:"i_arty"},
  {id:"af_ring_lead_box",name:"LLMC w/ Ring",cat:"i_arty"},
  {id:"af_dummy_dummy_lead_box",name:"LLMC w/ Shell",cat:"i_arty"},
  {id:"af_ice_lead_box",name:"LLMC w/ Snowflake",cat:"i_arty"},
  {id:"af_soul_lead_box",name:"LLMC w/ Soul",cat:"i_arty"},
  {id:"af_electra_sparkler_lead_box",name:"LLMC w/ Sparkler",cat:"i_arty"},
  {id:"af_sponge_lead_box",name:"LLMC w/ Sponge",cat:"i_arty"},
  {id:"af_blood_lead_box",name:"LLMC w/ Stone Blood",cat:"i_arty"},
  {id:"af_cristall_flower_lead_box",name:"LLMC w/ Stone Flower",cat:"i_arty"},
  {id:"af_vyvert_lead_box",name:"LLMC w/ Wrenched",cat:"i_arty"},
  {id:"af_lobster_eyes",name:"Lobster Eyes",cat:"i_arty"},
  {id:"prt_w_bolt_carrier_11",name:"Longitudinal-a sliding free bolt carrier [PP]",cat:"i_part"},
  {id:"bandit_exolight_outfit",name:"Looted exosuit",cat:"o_heavy"},
  {id:"bandit_nbc_outfit",name:"Looted NBC suit",cat:"o_medium"},
  {id:"bandit_scientific_outfit",name:"Looted SEVA suit",cat:"o_medium"},
  {id:"military_bandit_outfit",name:"Looted Skat-9 armoured suit",cat:"o_medium"},
  {id:"wpn_lr300",name:"LR-300ML",cat:"w_rifle"},
  {id:"wpn_lr300_camo",name:"LR-300ML (camouflaged)",cat:"w_rifle"},
  {id:"wpn_lr300_custom",name:"LR-300ML (custom)",cat:"w_rifle"},
  {id:"mutant_part_lurker_eye",name:"Lurker eye",cat:"i_mutant_part"},
  {id:"mutant_part_lurker_meat",name:"Lurker meat",cat:"i_mutant_part"},
  {id:"mutant_part_lurker_tail",name:"Lurker tail",cat:"i_mutant_part"},
  {id:"wpn_m16a2",name:"M16A2",cat:"w_rifle"},
  {id:"wpn_m16",name:"M16A4",cat:"w_rifle"},
  {id:"ammo_m209_bad",name:"M203",cat:"w_ammo"},
  {id:"ammo_m209_verybad",name:"M203",cat:"w_ammo"},
  {id:"ammo_m209",name:"M203 grenade",cat:"w_ammo"},
  {id:"wpn_fake_missile2",name:"M203 grenade",cat:"w_rifle"},
  {id:"wpn_addon_grenade_launcher_m203",name:"M203 grenade launcher",cat:"w_misc"},
  {id:"wpn_m249",name:"M249 SAW",cat:"w_sniper"},
  {id:"helm_m40",name:"M40 gas mask",cat:"o_helmet"},
  {id:"wpn_m4a1",name:"M4A1",cat:"w_rifle"},
  {id:"wpn_m4a1_camo",name:"M4A1 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_m4a1_custom",name:"M4A1 (custom)",cat:"w_rifle"},
  {id:"wpn_m4a1_freedom",name:"M4A1 (Freedom camouflage)",cat:"w_rifle"},
  {id:"wpn_m4",name:"M4A1 RAS",cat:"w_rifle"},
  {id:"helm_m50",name:"M50z gas mask",cat:"o_helmet"},
  {id:"wpn_m60",name:"M60",cat:"w_rifle"},
  {id:"wpn_m79",name:"M79",cat:"w_explosive"},
  {id:"wpn_knife5",name:"M9 bayonet",cat:"w_melee"},
  {id:"af_dummy_glassbeads",name:"Mama's Beads",cat:"i_arty"},
  {id:"af_mincer_meat",name:"Meat Chunk",cat:"i_arty"},
  {id:"af_medallion",name:"Medal",cat:"i_arty"},
  {id:"merc_ace_outfit",name:"Mercenary ACE scientific suit",cat:"o_medium"},
  {id:"specops_merc_outfit",name:"Mercenary B-5M armoured suit",cat:"o_medium"},
  {id:"merc_exo_outfit",name:"Mercenary exoskeleton",cat:"o_heavy"},
  {id:"merc_exolight_outfit",name:"Mercenary exosuit",cat:"o_heavy"},
  {id:"exo_merc_grass_outfit",name:"Mercenary grassland exosuit",cat:"o_heavy"},
  {id:"light_merc_outfit",name:"Mercenary IBAz suit",cat:"o_medium"},
  {id:"merc_outfit",name:"Mercenary LC suit",cat:"o_medium"},
  {id:"merc_fighter_outfit",name:"Mercenary LC-F suit",cat:"o_medium"},
  {id:"merc_scout_outfit",name:"Mercenary LC-S suit",cat:"o_medium"},
  {id:"merc_sunset_outfit",name:"Mercenary LCz suit",cat:"o_medium"},
  {id:"merc_jackal_outfit",name:"Mercenary LTS-J body suit",cat:"o_medium"},
  {id:"merc_coyote_outfit",name:"Mercenary MTS-C body suit",cat:"o_medium"},
  {id:"nbc_merc_outfit",name:"Mercenary NBC suit",cat:"o_medium"},
  {id:"merc_nosorog_outfit",name:"Mercenary Nosorog",cat:"o_heavy"},
  {id:"merc_combat_scientific_outfit",name:"Mercenary pathfinder",cat:"o_medium"},
  {id:"merc_scientific_armored_outfit",name:"Mercenary SEVA body armour",cat:"o_medium"},
  {id:"merc_scientific_outfit",name:"Mercenary SEVA suit",cat:"o_medium"},
  {id:"military_merc_outfit",name:"Mercenary Skat-9 armoured suit",cat:"o_medium"},
  {id:"merc_nighthunter_outfit",name:"Mercenary STS-N body armour",cat:"o_medium"},
  {id:"merc_wolven_outfit",name:"Mercenary STS-W body armour",cat:"o_medium"},
  {id:"exo_merc_urban_outfit",name:"Mercenary urban exosuit",cat:"o_heavy"},
  {id:"exo_merc_wood_outfit",name:"Mercenary woodland exosuit",cat:"o_heavy"},
  {id:"prt_i_scrap",name:"Metallic scrap",cat:"i_part"},
  {id:"prt_o_fabrics_4",name:"Mil-Spec textiles",cat:"i_part"},
  {id:"wpn_binoc",name:"Military binoculars",cat:"w_rifle"},
  {id:"army_outfit",name:"Military service outfit",cat:"o_medium"},
  {id:"military_exo_outfit",name:"Military stalker exoskeleton",cat:"o_heavy"},
  {id:"military_exolight_outfit",name:"Military stalker exosuit",cat:"o_heavy"},
  {id:"light_voen_outfit",name:"Military stalker IBAz suit",cat:"o_medium"},
  {id:"army_nosorog_outfit",name:"Military stalker Nosorog",cat:"o_heavy"},
  {id:"mine_new_blow",name:"Mine New Blow",cat:"i_misc"},
  {id:"mineral_water",name:"Mineral water",cat:"i_food"},
  {id:"mineral_water__1",name:"Mineral Water  1",cat:"i_food"},
  {id:"mineral_water__2",name:"Mineral Water  2",cat:"i_food"},
  {id:"mineral_water__3",name:"Mineral Water  3",cat:"i_food"},
  {id:"af_skull_miser",name:"Miser's skull",cat:"i_arty"},
  {id:"wpn_mk14",name:"Mk 14 EBR",cat:"w_sniper"},
  {id:"monolith_exo_outfit",name:"Monolith exoskeleton",cat:"o_heavy"},
  {id:"monolith_exolight_outfit",name:"Monolith exosuit",cat:"o_heavy"},
  {id:"light_monolit_outfit",name:"Monolith IBAz assault suit",cat:"o_medium"},
  {id:"monolith_nosorog_outfit",name:"Monolith Nosorog",cat:"o_heavy"},
  {id:"monolith_trenchcoat_outfit",name:"Monolith overcoat",cat:"o_medium"},
  {id:"monolith_scientific_light_outfit",name:"Monolith patchwork science suit",cat:"o_medium"},
  {id:"monolith_scientific_outfit",name:"Monolith scientific suit",cat:"o_medium"},
  {id:"military_monolit_outfit",name:"Monolith Skat-9 armoured suit",cat:"o_medium"},
  {id:"monolith_outfit",name:"Monolith X-18 suit",cat:"o_medium"},
  {id:"af_peas",name:"Moon",cat:"i_arty"},
  {id:"af_electra_moonlight",name:"Moonlight",cat:"i_arty"},
  {id:"wpn_mosin",name:"Mosin-Nagant",cat:"w_sniper"},
  {id:"af_moh",name:"Moss",cat:"i_arty"},
  {id:"wpn_mossberg590",name:"Mossberg 590A1",cat:"w_shotgun"},
  {id:"mp_exo_outfit",name:"Mp Exo Outfit",cat:"o_heavy"},
  {id:"mp_military_stalker_outfit",name:"Mp Military Stalker Outfit",cat:"o_medium"},
  {id:"mp_scientific_outfit",name:"Mp Scientific Outfit",cat:"o_medium"},
  {id:"wpn_mp133",name:"MP-133",cat:"w_shotgun"},
  {id:"wpn_mp153",name:"MP-153",cat:"w_shotgun"},
  {id:"wpn_mp412",name:"MP-412 Rex",cat:"w_pistol"},
  {id:"wpn_mp443",name:"MP-443 Grach",cat:"w_pistol"},
  {id:"wpn_mp5",name:"MP5A3",cat:"w_smg"},
  {id:"wpn_mp5_alt",name:"MP5A3 (alternate)",cat:"w_smg"},
  {id:"wpn_mp5_custom",name:"MP5A3 (custom)",cat:"w_smg"},
  {id:"wpn_mp5sd",name:"MP5SD6",cat:"w_smg"},
  {id:"wpn_mp5sd_custom",name:"MP5SD6 (custom)",cat:"w_smg"},
  {id:"wpn_mp5sd_new",name:"MP5SD6 (new)",cat:"w_smg"},
  {id:"wpn_mp7",name:"MP7",cat:"w_smg"},
  {id:"mutant_part_crow_beak",name:"Mutated crow beak",cat:"i_mutant_part"},
  {id:"wpn_sil_nato",name:"NATO suppressor",cat:"w_misc"},
  {id:"nbc_outfit",name:"NBC suit",cat:"o_medium"},
  {id:"vodka",name:"Nemiroff vodka",cat:"i_drink"},
  {id:"af_night_star",name:"Nightstar",cat:"i_arty"},
  {id:"ammo_batteries",name:"none",cat:"w_ammo"},
  {id:"ammo_batteries_ccell",name:"none",cat:"w_ammo"},
  {id:"ammo_batteries_dead",name:"none",cat:"w_ammo"},
  {id:"wpn_knife2",name:"NR-40 scout's knife",cat:"w_melee"},
  {id:"ammo_og-7b_bad",name:"OG-7V",cat:"w_ammo"},
  {id:"ammo_og-7b_verybad",name:"OG-7V",cat:"w_ammo"},
  {id:"ammo_og-7b",name:"OG-7V warhead",cat:"w_ammo"},
  {id:"headlamp",name:"Old head lamp",cat:"i_misc"},
  {id:"wpn_kiparis",name:"OTs-02 Kiparis",cat:"w_smg"},
  {id:"wpn_svu",name:"OTs-03 SVU",cat:"w_sniper"},
  {id:"wpn_svu_alt",name:"OTs-03 SVU (alternate)",cat:"w_sniper"},
  {id:"wpn_svu_nimble",name:"OTs-03A SVU-A",cat:"w_sniper"},
  {id:"wpn_groza",name:"OTs-14 Groza",cat:"w_rifle"},
  {id:"wpn_groza_nimble",name:"OTs-14-1A Groza-1",cat:"w_rifle"},
  {id:"wpn_oc33",name:"OTs-33 Pernach",cat:"w_pistol"},
  {id:"trenchcoat_outfit",name:"Overcoat",cat:"o_medium"},
  {id:"kolbasa",name:"Pack of old meat",cat:"i_food"},
  {id:"prt_i_paper",name:"Paper sheets",cat:"i_part"},
  {id:"svoboda_exo_outfit",name:"Paragon of Freedom",cat:"o_heavy"},
  {id:"bandit_scientific_dark_outfit",name:"Patchwork closed cycle apparatus",cat:"o_medium"},
  {id:"wpn_pb",name:"PB",cat:"w_pistol"},
  {id:"wpn_pb_custom",name:"PB (modern)",cat:"w_pistol"},
  {id:"prt_o_retardant_13",name:"PBI-blended fabrics",cat:"i_part"},
  {id:"prt_o_retardant_14",name:"PBI-blended fabrics w/ polyester treatment",cat:"i_part"},
  {id:"wpn_sil_pbs1",name:"PBS-1 suppressor",cat:"w_misc"},
  {id:"wpn_sil_pbs4",name:"PBS-4 suppressor",cat:"w_misc"},
  {id:"device_pda",name:"PDA",cat:"i_device"},
  {id:"device_pda_1",name:"PDA",cat:"i_device"},
  {id:"itm_pda_common",name:"PDA",cat:"i_misc"},
  {id:"device_pda_2",name:"PDA (Version 2.0)",cat:"i_device"},
  {id:"device_pda_3",name:"PDA (Version 3.1)",cat:"i_device"},
  {id:"journal",name:"Personal journal",cat:"i_misc"},
  {id:"mine",name:"PFM-1 scatterable anti-personnel mine",cat:"i_misc"},
  {id:"mine_new",name:"PFM-1 scatterable anti-personnel mine",cat:"i_misc"},
  {id:"af_star_phantom",name:"Phantom star",cat:"i_arty"},
  {id:"picture_woman",name:"Photo of a loved one",cat:"i_misc"},
  {id:"af_pin",name:"Pin",cat:"i_arty"},
  {id:"wpn_pkm",name:"PKM",cat:"w_rifle"},
  {id:"wpn_pkp",name:"PKP Pecheneg",cat:"w_rifle"},
  {id:"prt_i_plastic",name:"Plastic film",cat:"i_part"},
  {id:"jar",name:"Plastic jar",cat:"i_misc"},
  {id:"wpn_pm",name:"PM",cat:"w_pistol"},
  {id:"wpn_pm_custom",name:"PM (custom)",cat:"w_pistol"},
  {id:"wpn_pmm",name:"PMM",cat:"w_pistol"},
  {id:"wpn_addon_scope_po4x34",name:"PO4x34 scope",cat:"w_misc"},
  {id:"prt_o_ballistic_14",name:"Polyethylene armor plates (Improvised)",cat:"i_part"},
  {id:"prt_o_ballistic_17",name:"Polyethylene fibre layers w/ Polycarbonate inserts",cat:"i_part"},
  {id:"prt_o_ballistic_13",name:"Polyethylene lightweight armor plates",cat:"i_part"},
  {id:"prt_o_retardant_10",name:"Polymer sheets (barium-sulfate coating)",cat:"i_part"},
  {id:"prt_o_retardant_9",name:"Polymer sheets (bismuth-sulfate coating)",cat:"i_part"},
  {id:"wpn_dynamo_hand",name:"Portable Dynamo",cat:"w_rifle"},
  {id:"explo_metalcan_powder",name:"Powder can",cat:"i_misc"},
  {id:"wpn_bizon",name:"PP-19 Bizon",cat:"w_smg"},
  {id:"wpn_vityaz",name:"PP-19-01 Vityaz",cat:"w_rifle"},
  {id:"wpn_pp2000",name:"PP-2000",cat:"w_rifle"},
  {id:"helm_ppm88",name:"PPM-88 gas mask",cat:"o_helmet"},
  {id:"wpn_ppsh41",name:"PPSh-41",cat:"w_rifle"},
  {id:"wpn_ppsh41_rednew",name:"PPSh-41 (camo)",cat:"w_rifle"},
  {id:"wpn_ppsh41_woodnew",name:"PPSh-41 (modern)",cat:"w_rifle"},
  {id:"dolg_scientific_wood_outfit",name:"PS5-9Md pathfinder",cat:"o_medium"},
  {id:"dolg_scientific_red_outfit",name:"PS5-9Md scientific guard suit",cat:"o_medium"},
  {id:"dolg_scientific_outfit",name:"PS5-9Md universal scientific suit",cat:"o_medium"},
  {id:"specops_dolg_outfit",name:"PS5-B battle armour",cat:"o_medium"},
  {id:"dolg_specops_red_outfit",name:"PS5-B2 veteran battlesuit",cat:"o_medium"},
  {id:"dolg_red_outfit",name:"PS5-M hunter suit",cat:"o_medium"},
  {id:"dolg_proto_exo_outfit",name:"PS5-M proto-exoskeleton",cat:"o_heavy"},
  {id:"dolg_outfit",name:"PS5-M universal protection",cat:"o_medium"},
  {id:"nbc_dolg_outfit",name:"PS5-Md NBC suit",cat:"o_medium"},
  {id:"dolg_scout_outfit",name:"PS5-R scout vest",cat:"o_medium"},
  {id:"dolg_voin_outfit",name:"PS6-V warrior suit",cat:"o_medium"},
  {id:"mutant_part_fang_psevdodog",name:"Pseudodog fang",cat:"i_mutant_part"},
  {id:"mutant_part_psevdodog_meat",name:"Pseudodog meat",cat:"i_mutant_part"},
  {id:"mutant_part_psevdodog_tail",name:"Pseudodog tail",cat:"i_mutant_part"},
  {id:"mutant_part_pseudogigant_eye",name:"Pseudogiant eye",cat:"i_mutant_part"},
  {id:"mutant_part_pseudogigant_hand",name:"Pseudogiant hand",cat:"i_mutant_part"},
  {id:"wpn_addon_scope",name:"PSO-1M scope",cat:"w_misc"},
  {id:"wpn_addon_scope_m24",name:"PSO-1M scope",cat:"w_misc"},
  {id:"wpn_addon_scope_sv98",name:"PSO-1M scope",cat:"w_misc"},
  {id:"drug_psy_blockade",name:"Psy-block",cat:"i_medical"},
  {id:"mutant_part_psysucker_hand",name:"Psysucker hand",cat:"i_mutant_part"},
  {id:"mutant_part_psysucker_meat",name:"Psysucker meat",cat:"i_mutant_part"},
  {id:"dolg_exolight_outfit",name:"PSZ-10d Duty battlesuit",cat:"o_heavy"},
  {id:"exo_dolg_outfit",name:"PSZ-10d Duty battlesuit",cat:"o_heavy"},
  {id:"dolg_exo_outfit",name:"PSZ-10d exoskeleton",cat:"o_heavy"},
  {id:"dolg_nosorog_outfit",name:"PSZ-10d Nosorog",cat:"o_heavy"},
  {id:"exo_dolg_red_outfit",name:"PSZ-10d venator battlesuit",cat:"o_heavy"},
  {id:"exo_dolg_urban_outfit",name:"PSZ-10g urban battlesuit",cat:"o_heavy"},
  {id:"exo_dolg_wood_outfit",name:"PSZ-10l forest battlesuit",cat:"o_heavy"},
  {id:"dolg_pantsir_outfit",name:"PSZ-7p shell armour",cat:"o_medium"},
  {id:"dolg_heavy_outfit",name:"PSZ-9d body armour",cat:"o_heavy"},
  {id:"dolg_heavy_proto_exo_outfit",name:"PSZ-9d proto-exoskeleton",cat:"o_heavy"},
  {id:"dolg_heavy_redline_outfit",name:"PSZ-9kl command armour",cat:"o_heavy"},
  {id:"wpn_addon_scope_mosin",name:"PU scope",cat:"w_misc"},
  {id:"wpn_addon_scope_pu",name:"PU scope",cat:"w_misc"},
  {id:"vodka2",name:"Putinka vodka",cat:"i_drink"},
  {id:"prt_o_retardant_6",name:"PVC/carbon-fibre fabrics",cat:"i_part"},
  {id:"prt_o_retardant_5",name:"PVC/Rubber coated fabrics",cat:"i_part"},
  {id:"itm_actor_backpack",name:"Quick Release System",cat:"i_attach"},
  {id:"itm_actor_backpack_mlr",name:"Quick Release System",cat:"i_attach"},
  {id:"drug_radioprotector",name:"Radioprotectant",cat:"i_medical"},
  {id:"ramrod_tool__1",name:"Ramrod Tool  1",cat:"i_tool"},
  {id:"rasp_tool__1",name:"Rasp Tool  1",cat:"i_tool"},
  {id:"redline_novice_outfit",name:"Redline leather jacket",cat:"o_medium"},
  {id:"helm_respirator",name:"Refitted PBF gas mask kit",cat:"o_helmet"},
  {id:"helm_respirator_old",name:"Refitted PBF gas mask kit",cat:"o_helmet"},
  {id:"prt_o_ballistic_20",name:"Reinforced carbon fibre layers",cat:"i_part"},
  {id:"prt_o_ballistic_12",name:"Reinforced Kevlar K119 plates",cat:"i_part"},
  {id:"prt_o_ballistic_18",name:"Reinforced polyethylene fibre layers",cat:"i_part"},
  {id:"wpn_remington700",name:"Remington 700",cat:"w_sniper"},
  {id:"wpn_remington870",name:"Remington 870",cat:"w_shotgun"},
  {id:"renegade_exo_outfit",name:"Renegade exoskeleton",cat:"o_heavy"},
  {id:"renegademerc_outfit",name:"Renegade LC suit",cat:"o_medium"},
  {id:"renegade_scientific_outfit",name:"Renegade SEVA suit",cat:"o_medium"},
  {id:"helm_resp",name:"Respirator",cat:"o_helmet"},
  {id:"detector_radio",name:"RF receiver",cat:"i_device"},
  {id:"wpn_rg-6",name:"RG-6",cat:"w_rifle"},
  {id:"grenade_rgd5",name:"RGD-5 grenade",cat:"w_explosive"},
  {id:"af_ring",name:"Ring",cat:"i_arty"},
  {id:"mutant_part_tushkano_meat",name:"Rodent meat",cat:"i_mutant_part"},
  {id:"rope",name:"Rope",cat:"i_misc"},
  {id:"prt_w_bolt_3",name:"Rotating locking head [2 locks][K]",cat:"i_part"},
  {id:"prt_w_bolt_2",name:"Rotating locking head [2 locks][P]",cat:"i_part"},
  {id:"prt_w_bolt_4",name:"Rotating locking head [2 locks][V]",cat:"i_part"},
  {id:"prt_w_bolt_6",name:"Rotating locking head [2 locks][�]",cat:"i_part"},
  {id:"prt_w_bolt_13",name:"Rotating locking head [2 locks][�][NATO]",cat:"i_part"},
  {id:"prt_w_bolt_5",name:"Rotating locking head [3 locks][V]",cat:"i_part"},
  {id:"prt_w_bolt_7",name:"Rotating locking head [4 locks][AS]",cat:"i_part"},
  {id:"prt_w_bolt_8",name:"Rotating locking head [6 locks][�]",cat:"i_part"},
  {id:"prt_w_bolt_9",name:"Rotating locking head [7 locks][�]",cat:"i_part"},
  {id:"prt_w_bolt_10",name:"Rotating locking head [8 locks][�]",cat:"i_part"},
  {id:"prt_w_bolt_14",name:"Rotating locking head [�/PP]",cat:"i_part"},
  {id:"roubles",name:"Roubles",cat:"i_misc"},
  {id:"wpn_rpd",name:"RPD",cat:"w_rifle"},
  {id:"wpn_rpg7",name:"RPG-7",cat:"w_explosive"},
  {id:"wpn_rpk",name:"RPK",cat:"w_rifle"},
  {id:"wpn_rpk74",name:"RPK-74N",cat:"w_rifle"},
  {id:"prt_i_rubber",name:"Rubber",cat:"i_part"},
  {id:"chocolate_p",name:"Russian chocolate (half-consumed)",cat:"i_misc"},
  {id:"ration_ru",name:"Russian IRP-B combat ration",cat:"i_food"},
  {id:"porn",name:"Russian PLAYBOY",cat:"i_misc"},
  {id:"wpn_saiga12s",name:"Saiga-12S",cat:"w_shotgun"},
  {id:"wpn_trg",name:"Sako TRG-42",cat:"w_rifle"},
  {id:"af_sandstone",name:"Sandstone",cat:"i_arty"},
  {id:"af_zhelch",name:"Scar",cat:"i_arty"},
  {id:"ecolog_exo_outfit",name:"Scientific exoskeleton",cat:"o_heavy"},
  {id:"medkit_ai3",name:"Scientific medical package",cat:"i_medical"},
  {id:"medkit_scientic",name:"Scientific medkit",cat:"i_medical"},
  {id:"svoboda_heavy_outfit_2",name:"Sentinel of Freedom",cat:"o_heavy"},
  {id:"af_serofim",name:"Seraphim",cat:"i_arty"},
  {id:"scientific_outfit",name:"SEVA bodysuit",cat:"o_medium"},
  {id:"af_dummy_dummy",name:"Shell",cat:"i_arty"},
  {id:"wpn_sig220",name:"SIG P220",cat:"w_pistol"},
  {id:"wpn_sig220_custom",name:"SIG P220 (custom)",cat:"w_pistol"},
  {id:"wpn_sig550",name:"SIG SG550",cat:"w_rifle"},
  {id:"wpn_sig550_camo",name:"SIG SG550 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_sig550_custom",name:"SIG SG550 (custom)",cat:"w_rifle"},
  {id:"wpn_sig550_luckygun",name:"SIG SG550 Arrow",cat:"w_rifle"},
  {id:"wpn_sig550_sniper",name:"SIG SG550-1 Sniper",cat:"w_rifle"},
  {id:"wpn_sig552",name:"SIG SG552 Commando",cat:"w_rifle"},
  {id:"af_signet",name:"Signet",cat:"i_arty"},
  {id:"greh_trenchcoat_outfit",name:"Sin heavy overcoat",cat:"o_medium"},
  {id:"prt_w_trigger_components_4",name:"Single fire mode trigger mechanism with firing pin",cat:"i_part"},
  {id:"prt_w_p_trigger_1",name:"Single-action trigger mechanism",cat:"i_part"},
  {id:"prt_w_trigger_components_1",name:"Single-mode hammer type trigger",cat:"i_part"},
  {id:"military_outfit",name:"Skat-9 armoured suit",cat:"o_medium"},
  {id:"military_proto_exo_outfit",name:"Skat-9 proto-exoskeleton",cat:"o_heavy"},
  {id:"wpn_vz61",name:"Skorpion vz.61",cat:"w_smg"},
  {id:"wpn_vz61_alt",name:"Skorpion vz.61 (alternate)",cat:"w_smg"},
  {id:"wpn_vz61_camo",name:"Skorpion vz.61 (camouflaged)",cat:"w_smg"},
  {id:"wpn_vz61_freedom",name:"Skorpion vz.61 (Freedom camouflage)",cat:"w_smg"},
  {id:"wpn_sks",name:"SKS",cat:"w_rifle"},
  {id:"wpn_sks_modern",name:"SKS (modern)",cat:"w_rifle"},
  {id:"itm_sleepbag",name:"Sleeping bag",cat:"i_misc"},
  {id:"prt_w_bolt_carrier_4",name:"Sliding bolt carrier with a locking bias",cat:"i_part"},
  {id:"prt_w_bolt_carrier_6",name:"Sliding bolt carrier with locking bolt",cat:"i_part"},
  {id:"prt_w_bolt_carrier_10",name:"Sliding bolt carrier with turning bolt lock [NATO]",cat:"i_part"},
  {id:"prt_w_bolt_carrier_3",name:"Sliding bolt carrier with turning bolt lock [NATO]",cat:"i_part"},
  {id:"prt_w_bolt_carrier_1",name:"Sliding bolt carrier with turning bolt lock [Russia]",cat:"i_part"},
  {id:"prt_w_bolt_carrier_2",name:"Sliding bolt carrier with turning bolt lock [Russia]",cat:"i_part"},
  {id:"radio",name:"Small radio",cat:"i_misc"},
  {id:"grenade_smoke",name:"Smoke grenade",cat:"w_explosive"},
  {id:"sausage",name:"Smoked sausage",cat:"i_food"},
  {id:"mutant_part_snork_hand",name:"Snork hand",cat:"i_mutant_part"},
  {id:"mutant_part_snork_leg",name:"Snork leg",cat:"i_mutant_part"},
  {id:"mutant_part_snork_mask",name:"Snork mask",cat:"i_mutant_part"},
  {id:"af_ice",name:"Snowflake",cat:"i_arty"},
  {id:"underwear",name:"Soaked underwear",cat:"i_misc"},
  {id:"af_soul",name:"Soul",cat:"i_arty"},
  {id:"af_kislushka",name:"Sourpuss",cat:"i_arty"},
  {id:"af_electra_sparkler",name:"Sparkler",cat:"i_arty"},
  {id:"water_drink",name:"Sparkling water",cat:"i_drink"},
  {id:"wpn_spas12",name:"SPAS-12",cat:"w_shotgun"},
  {id:"wpn_spas12_custom",name:"SPAS-12 (custom)",cat:"w_shotgun"},
  {id:"wpn_spas12_nimble",name:"SPAS-12 (modern)",cat:"w_shotgun"},
  {id:"wpn_knife4",name:"Spetsnaz switchblade",cat:"w_melee"},
  {id:"helm_battle",name:"Sphere M12 helmet",cat:"o_helmet"},
  {id:"helm_tactic",name:"Sphere-08 helmet",cat:"o_helmet"},
  {id:"af_spaika",name:"Spike",cat:"i_arty"},
  {id:"af_sponge",name:"Sponge",cat:"i_arty"},
  {id:"wpn_sr25",name:"SR-25",cat:"w_sniper"},
  {id:"wpn_sil_sr25",name:"SR-25 suppressor",cat:"w_misc"},
  {id:"wpn_sil_vihr",name:"SR-3M suppressor",cat:"w_misc"},
  {id:"wpn_vihr",name:"SR-3M Vikhr",cat:"w_rifle"},
  {id:"ecolog_outfit_white",name:"SSP-99 Diamond",cat:"o_sci"},
  {id:"ecolog_outfit_orange",name:"SSP-99 Ecologist",cat:"o_sci"},
  {id:"helm_protective",name:"SSP-99 screen helmet",cat:"o_helmet"},
  {id:"ecolog_outfit_yello",name:"SSP-99 Topaz",cat:"o_sci"},
  {id:"ecolog_outfit_blue",name:"SSP-99M Sapphire",cat:"o_sci"},
  {id:"ecolog_outfit_green",name:"SSP-99M suit",cat:"o_sci"},
  {id:"ecolog_outfit_red",name:"SSP-99� Ruby",cat:"o_sci"},
  {id:"steel_wool",name:"Steel wool",cat:"i_misc"},
  {id:"wpn_aug",name:"Steyr AUG A1",cat:"w_rifle"},
  {id:"wpn_aug_freedom",name:"Steyr AUG A1 (camouflaged)",cat:"w_rifle"},
  {id:"wpn_aug_custom",name:"Steyr AUG A1 (custom)",cat:"w_rifle"},
  {id:"wpn_aug_merc",name:"Steyr AUG A1 (customised)",cat:"w_rifle"},
  {id:"wpn_aug_modern",name:"Steyr AUG A1 (modern)",cat:"w_rifle"},
  {id:"wpn_aug_a3",name:"Steyr AUG A3",cat:"w_rifle"},
  {id:"vodka_quality",name:"Stolichnaya vodka",cat:"i_drink"},
  {id:"af_blood",name:"Stone Blood",cat:"i_arty"},
  {id:"af_cristall_flower",name:"Stone Flower",cat:"i_arty"},
  {id:"energy_drink",name:"Strong energy drink",cat:"i_drink"},
  {id:"af_sun",name:"Sun",cat:"i_arty"},
  {id:"prt_w_bolt_11",name:"Supercharger with hammer from a double-barrel shotgun [R]",cat:"i_part"},
  {id:"af_surge",name:"Surge suppressor",cat:"i_arty"},
  {id:"helm_hardhat",name:"Surplus steel helmet",cat:"o_helmet"},
  {id:"helm_hardhat_snag",name:"Surplus steel helmet",cat:"o_helmet"},
  {id:"wpn_sv98",name:"SV98",cat:"w_rifle"},
  {id:"wpn_sv98_custom",name:"SV98 (custom)",cat:"w_rifle"},
  {id:"detector_scientific",name:"Svarog detector",cat:"i_device"},
  {id:"wpn_svd",name:"SVD",cat:"w_sniper"},
  {id:"wpn_svd_custom",name:"SVD (customised)",cat:"w_sniper"},
  {id:"wpn_svt40",name:"SVT-40",cat:"w_rifle"},
  {id:"wpn_svt40_modern",name:"SVT-40 (modern)",cat:"w_rifle"},
  {id:"swiss_knife",name:"Swiss knife",cat:"i_misc"},
  {id:"af_tapeworm",name:"Tapeworm",cat:"i_arty"},
  {id:"mirror",name:"Telescopic mirror",cat:"i_misc"},
  {id:"prt_i_textolite",name:"Textolite base",cat:"i_part"},
  {id:"wpn_sil_tgp-a",name:"TGP-A suppressor",cat:"w_misc"},
  {id:"grenade_gd-05",name:"Thermite grenade",cat:"w_explosive"},
  {id:"af_repei",name:"Thistle",cat:"i_arty"},
  {id:"af_grid",name:"Titanium grid",cat:"i_arty"},
  {id:"equ_tourist_pack",name:"Tourist backpack",cat:"i_misc"},
  {id:"novice_outfit_tourist",name:"Tourist�s jacket",cat:"o_medium"},
  {id:"wpn_wincheaster1300",name:"TOZ-194",cat:"w_shotgun"},
  {id:"wpn_toz34",name:"TOZ-34",cat:"w_shotgun"},
  {id:"wpn_toz34_obrez_custom",name:"TOZ-34 (custom sawn-off)",cat:"w_shotgun"},
  {id:"wpn_toz34_custom",name:"TOZ-34 (custom)",cat:"w_shotgun"},
  {id:"wpn_toz34_obrez_decor",name:"TOZ-34 (decorated sawn-off)",cat:"w_shotgun"},
  {id:"wpn_toz34_decor",name:"TOZ-34 (decorated)",cat:"w_shotgun"},
  {id:"wpn_toz34_obrez",name:"TOZ-34 (sawn-off)",cat:"w_shotgun"},
  {id:"wpn_bm16_full",name:"TOZ-66",cat:"w_pistol"},
  {id:"wpn_bm16_alt",name:"TOZ-66 (alternate sawn-off)",cat:"w_shotgun"},
  {id:"wpn_bm16_full_alt",name:"TOZ-66 (alternate)",cat:"w_pistol"},
  {id:"wpn_bm16",name:"TOZ-66 (sawn-off)",cat:"w_shotgun"},
  {id:"equ_small_military_pack",name:"Travel backpack",cat:"i_misc"},
  {id:"prt_w_trigger_components_6",name:"Trigger mechanism with hammer [R]",cat:"i_part"},
  {id:"prt_w_trigger_components_3",name:"Triple fire mode trigger mechanism with hammer",cat:"i_part"},
  {id:"wpn_tt33",name:"TT-33",cat:"w_pistol"},
  {id:"wpn_tt33_modern",name:"TT-33 (modern)",cat:"w_pistol"},
  {id:"mutant_part_tushkano_head",name:"Tushkano head",cat:"i_mutant_part"},
  {id:"wpn_type63",name:"Type 63",cat:"w_rifle"},
  {id:"beer",name:"Ukrainian beer",cat:"i_misc"},
  {id:"ration_ukr",name:"Ukrainian combat ration",cat:"i_food"},
  {id:"porn2",name:"Ukrainian MAXIM",cat:"i_misc"},
  {id:"wpn_ump45",name:"UMP45",cat:"w_rifle"},
  {id:"wpn_ump45_custom",name:"UMP45 (custom)",cat:"w_rifle"},
  {id:"isg_exo_outfit",name:"UNISG exoskeleton",cat:"o_heavy"},
  {id:"isg_exolight_outfit",name:"UNISG exosuit",cat:"o_heavy"},
  {id:"light_isg_outfit",name:"UNISG IBAz suit",cat:"o_medium"},
  {id:"isg_lcs_outfit",name:"UNISG LC suit",cat:"o_medium"},
  {id:"isg_lcs_camo_outfit",name:"UNISG LC-C suit",cat:"o_medium"},
  {id:"isg_lcs_urban_outfit",name:"UNISG LC-UC suit",cat:"o_medium"},
  {id:"isg_outfit",name:"UNISG Mk 1 tactical body armour",cat:"o_medium"},
  {id:"isg_camo_outfit",name:"UNISG Mk 2 tactical body armour",cat:"o_medium"},
  {id:"isg_nosorog_outfit",name:"UNISG Nosorog",cat:"o_heavy"},
  {id:"isg_scientific_outfit",name:"UNISG SEVA suit",cat:"o_medium"},
  {id:"isg_proto_exo_outfit",name:"UNISG tactical proto-exoskeleton",cat:"o_heavy"},
  {id:"wpn_addon_silencer",name:"US Army smallbore rifle suppressor",cat:"w_misc"},
  {id:"wpn_usas12",name:"USAS-12",cat:"w_shotgun"},
  {id:"wpn_usp_match",name:"USP Match",cat:"w_pistol"},
  {id:"wpn_usp",name:"USP45",cat:"w_pistol"},
  {id:"wpn_usp_custom",name:"USP45 (custom)",cat:"w_pistol"},
  {id:"detector_elite",name:"Veles detector",cat:"i_device"},
  {id:"drug_coagulant",name:"Vinca",cat:"i_medical"},
  {id:"ammo_vog-25_bad",name:"VOG-25",cat:"w_ammo"},
  {id:"ammo_vog-25_verybad",name:"VOG-25",cat:"w_ammo"},
  {id:"ammo_vog-25",name:"VOG-25 grenade",cat:"w_ammo"},
  {id:"wpn_fake_missile",name:"VOG-25 grenade",cat:"w_rifle"},
  {id:"af_monolith",name:"Volat Emerald",cat:"i_arty"},
  {id:"greh_ps5_outfit",name:"Volos flak armour",cat:"o_medium"},
  {id:"wpn_vsk94",name:"VSK-94",cat:"w_rifle"},
  {id:"wpn_vintorez",name:"VSS Vintorez",cat:"w_sniper"},
  {id:"wpn_vintorez_alt",name:"VSS Vintorez (alternate)",cat:"w_sniper"},
  {id:"wpn_vssk",name:"VSSK Vykhlop",cat:"w_sniper"},
  {id:"greh_exo_outfit",name:"Vyraj power armour",cat:"o_heavy"},
  {id:"greh_armored_camo_outfit",name:"Vyriy flak armour",cat:"o_medium"},
  {id:"walkie",name:"Walkie talkie",cat:"i_misc"},
  {id:"wpn_walther",name:"Walther P99",cat:"w_pistol"},
  {id:"wpn_walther_custom",name:"Walther P99 (custom)",cat:"w_pistol"},
  {id:"wpn_wa2000",name:"Walther WA 2000",cat:"w_sniper"},
  {id:"svoboda_exolight_outfit",name:"Warrior of Freedom",cat:"o_heavy"},
  {id:"svoboda_scientific_outfit",name:"Watchman of Freedom",cat:"o_medium"},
  {id:"welding_goggles",name:"Welding goggles",cat:"i_misc"},
  {id:"svoboda_light_outfit",name:"Wind of Freedom",cat:"o_medium"},
  {id:"prt_i_wood",name:"Wooden parts",cat:"i_part"},
  {id:"exo_wood_outfit",name:"Woodland exosuit",cat:"o_heavy"},
  {id:"wpn_addon_scope_acog",name:"Wpn Addon Scope Acog",cat:"w_misc"},
  {id:"wpn_addon_scope_acog_night",name:"Wpn Addon Scope Acog Night",cat:"w_misc"},
  {id:"wpn_addon_scope_detector",name:"Wpn Addon Scope Detector",cat:"w_misc"},
  {id:"wpn_addon_scope_moist",name:"Wpn Addon Scope Moist",cat:"w_misc"},
  {id:"wpn_addon_scope_night",name:"Wpn Addon Scope Night",cat:"w_misc"},
  {id:"wpn_addon_scope_susat",name:"Wpn Addon Scope Susat",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_custom",name:"Wpn Addon Scope Susat Custom",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_dusk",name:"Wpn Addon Scope Susat Dusk",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_moist",name:"Wpn Addon Scope Susat Moist",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_night",name:"Wpn Addon Scope Susat Night",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_worn",name:"Wpn Addon Scope Susat Worn",cat:"w_misc"},
  {id:"wpn_addon_scope_susat_x1.6",name:"Wpn Addon Scope Susat X1.6",cat:"w_misc"},
  {id:"wpn_addon_scope_vsk",name:"Wpn Addon Scope Vsk",cat:"w_misc"},
  {id:"wpn_addon_scope_worn",name:"Wpn Addon Scope Worn",cat:"w_misc"},
  {id:"wpn_addon_scope_ww2",name:"Wpn Addon Scope Ww2",cat:"w_misc"},
  {id:"wpn_addon_scope_ww2_moist",name:"Wpn Addon Scope Ww2 Moist",cat:"w_misc"},
  {id:"wpn_addon_scope_ww2_worn",name:"Wpn Addon Scope Ww2 Worn",cat:"w_misc"},
  {id:"wpn_addon_scope_x2.7",name:"Wpn Addon Scope X2.7",cat:"w_misc"},
  {id:"wpn_addon_scope_zf4_moist",name:"Wpn Addon Scope Zf4 Moist",cat:"w_misc"},
  {id:"wpn_addon_scope_zf4_worn",name:"Wpn Addon Scope Zf4 Worn",cat:"w_misc"},
  {id:"wpn_fake_missile1",name:"Wpn Fake Missile1",cat:"w_rifle"},
  {id:"wpn_famas3",name:"Wpn Famas3",cat:"w_rifle"},
  {id:"wpn_knife_mp",name:"Wpn Knife Mp",cat:"w_melee"},
  {id:"wpn_mine",name:"Wpn Mine",cat:"w_rifle"},
  {id:"wpn_rpg7_missile",name:"Wpn Rpg7 Missile",cat:"w_explosive"},
  {id:"wpn_upd",name:"Wpn Upd",cat:"w_rifle"},
  {id:"af_vyvert",name:"Wrenched",cat:"i_arty"},
  {id:"monolith_proto_exo_outfit",name:"X-18 proto-exoskeleton",cat:"o_heavy"},
  {id:"wpn_xm8",name:"XM8",cat:"w_rifle"},
  {id:"yadylin",name:"Yadulin",cat:"i_medical"},
  {id:"wpn_addon_scope_g43",name:"ZF-4 scope",cat:"w_misc"},
  {id:"wpn_addon_scope_zf4",name:"ZF-4 scope",cat:"w_misc"},
  {id:"mutant_part_zombi_hand",name:"Zombie hand",cat:"i_mutant_part"},
  {id:"wpn_pkm_zulus",name:"Zulu's PKM",cat:"w_rifle"},
];
