// Auto-generated by extract_weapon_compat.py
// Maps weapon section → compatible ammo, scopes, silencer, grenade launcher
window.WEAPON_COMPAT = {
  "wpn_9a91": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9a91"
    ]
  },
  "wpn_abakan": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ]
  },
  "wpn_abakan_camo": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ]
  },
  "wpn_ace21": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aek": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_aek_camo": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_aek_duty": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_ak101": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak101_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak102": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak103": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak103_camo": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak104": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_atg"
    ]
  },
  "wpn_ak105": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak12": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74_alt": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74_custom": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74_modern": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74_old": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m_alt": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m_camo": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m_custom": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m_duty": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74m_pka": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_ak74u": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs4"
    ]
  },
  "wpn_ak74u_camo": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs4"
    ]
  },
  "wpn_ak74u_custom": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs4"
    ]
  },
  "wpn_ak74u_old": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs4"
    ]
  },
  "wpn_ak74u_snag": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs4"
    ]
  },
  "wpn_akm": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_akms": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_akms_alt": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_aks": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_aks74": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_aks74_new": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_aps": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_ash12": {
    "ammo": [
      "ammo_12.7x55_fmj",
      "ammo_12.7x55_fmj_bad",
      "ammo_12.7x55_fmj_verybad",
      "ammo_12.7x55_ap",
      "ammo_12.7x55_ap_bad",
      "ammo_12.7x55_ap_verybad"
    ]
  },
  "wpn_aug": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aug_a3": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aug_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aug_freedom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aug_merc": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_aug_modern": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_beretta": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_beretta_alt": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_beretta_camo": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_beretta_modern": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_bizon": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_bm16": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_bm16_alt": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_bm16_full": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_bm16_full_alt": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_colt1911": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_alt": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_camo": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_duty": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_merc": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_modern": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt1911_new": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_colt_kimber": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_cz52": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_cz75": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_cz75_auto": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_desert_eagle": {
    "ammo": [
      "ammo_357_hp_mag",
      "ammo_357_hp_mag_bad",
      "ammo_357_hp_mag_verybad"
    ]
  },
  "wpn_desert_eagle_custom": {
    "ammo": [
      "ammo_357_hp_mag",
      "ammo_357_hp_mag_bad",
      "ammo_357_hp_mag_verybad"
    ]
  },
  "wpn_desert_eagle_modern": {
    "ammo": [
      "ammo_357_hp_mag",
      "ammo_357_hp_mag_bad",
      "ammo_357_hp_mag_verybad"
    ]
  },
  "wpn_fal": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_famas3": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fn2000": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fn2000_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fn2000_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fn2000_nimble": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fn57": {
    "ammo": [
      "ammo_5.7x28_ss190",
      "ammo_5.7x28_ss190_bad",
      "ammo_5.7x28_ss190_verybad",
      "ammo_5.7x28_ss195",
      "ammo_5.7x28_ss195_bad",
      "ammo_5.7x28_ss195_verybad"
    ],
    "silencer": [
      "wpn_sil_57"
    ]
  },
  "wpn_fnc": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_fnp45": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_fnp45_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_fnx45": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_fnx45_alt": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_fnx45_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_fort": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_fort500": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_g3": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_g36": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_g36_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_g36k": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_g3sg1": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ]
  },
  "wpn_g43": {
    "ammo": [
      "ammo_7.92x33_fmj",
      "ammo_7.92x33_fmj_bad",
      "ammo_7.92x33_fmj_verybad",
      "ammo_7.92x33_ap",
      "ammo_7.92x33_ap_bad",
      "ammo_7.92x33_ap_verybad"
    ]
  },
  "wpn_galil": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_galil_custom": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_galil_modern": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_gauss": {
    "ammo": [
      "ammo_gauss",
      "ammo_gauss_bad",
      "ammo_gauss_verybad"
    ]
  },
  "wpn_glock": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_glock_custom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_glock_modern": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_groza": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ]
  },
  "wpn_groza_nimble": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ],
    "gl": [
      "ammo_vog-25",
      "ammo_vog-25_bad",
      "ammo_vog-25_verybad"
    ]
  },
  "wpn_gsh18": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_gsh18_custom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_hk416": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_hk417": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_hpsa": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_hpsa_alt": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_k98": {
    "ammo": [
      "ammo_7.92x33_fmj",
      "ammo_7.92x33_fmj_bad",
      "ammo_7.92x33_fmj_verybad",
      "ammo_7.92x33_ap",
      "ammo_7.92x33_ap_bad",
      "ammo_7.92x33_ap_verybad"
    ]
  },
  "wpn_kiparis": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_l85": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85_alt": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85_modern": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85a2": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85a2_alt": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85a2_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l85a2_modern": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_l96a1": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ]
  },
  "wpn_l96a1m": {
    "ammo": [
      "ammo_magnum_300",
      "ammo_magnum_300_bad",
      "ammo_magnum_300_verybad"
    ]
  },
  "wpn_lr300": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_lr300_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_lr300_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m16": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m16a2": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m249": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ]
  },
  "wpn_m4": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m4a1": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m4a1_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m4a1_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m4a1_freedom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_m60": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ]
  },
  "wpn_m82": {
    "ammo": [
      "ammo_12.7x55_fmj",
      "ammo_12.7x55_fmj_bad",
      "ammo_12.7x55_fmj_verybad",
      "ammo_12.7x55_ap",
      "ammo_12.7x55_ap_bad",
      "ammo_12.7x55_ap_verybad"
    ]
  },
  "wpn_mk14": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_mosin": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_mossberg590": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_mp133": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_mp153": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_mp412": {
    "ammo": [
      "ammo_357_hp_mag",
      "ammo_357_hp_mag_bad",
      "ammo_357_hp_mag_verybad"
    ]
  },
  "wpn_mp443": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_mp5": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_mp5_alt": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_mp5_custom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_mp5sd": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_mp5sd_custom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_mp5sd_new": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_mp7": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_oc33": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_p90": {
    "ammo": [
      "ammo_5.7x28_ss190",
      "ammo_5.7x28_ss190_bad",
      "ammo_5.7x28_ss190_verybad",
      "ammo_5.7x28_ss195",
      "ammo_5.7x28_ss195_bad",
      "ammo_5.7x28_ss195_verybad"
    ],
    "silencer": [
      "wpn_sil_57"
    ]
  },
  "wpn_pb": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_6p9"
    ]
  },
  "wpn_pb_custom": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_6p9"
    ]
  },
  "wpn_pkm": {
    "ammo": [
      "ammo_pkm_100",
      "ammo_pkm_100_bad",
      "ammo_pkm_100_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad"
    ]
  },
  "wpn_pkm_zulus": {
    "ammo": [
      "ammo_pkm_100",
      "ammo_pkm_100_bad",
      "ammo_pkm_100_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad"
    ]
  },
  "wpn_pkp": {
    "ammo": [
      "ammo_pkm_100",
      "ammo_pkm_100_bad",
      "ammo_pkm_100_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad"
    ]
  },
  "wpn_pm": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_pm_custom": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_pmm": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_pp2000": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9mm"
    ]
  },
  "wpn_ppsh41": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_ppsh41_rednew": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_ppsh41_woodnew": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_protecta": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_protecta_aim": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_protecta_camo": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_protecta_custom": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_protecta_nimble": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_remington700": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ]
  },
  "wpn_remington870": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_rpd": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ]
  },
  "wpn_rpk": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ]
  },
  "wpn_rpk74": {
    "ammo": [
      "ammo_5.45x39_fmj",
      "ammo_5.45x39_fmj_bad",
      "ammo_5.45x39_fmj_verybad",
      "ammo_5.45x39_ep",
      "ammo_5.45x39_ep_bad",
      "ammo_5.45x39_ep_verybad",
      "ammo_5.45x39_ap",
      "ammo_5.45x39_ap_bad",
      "ammo_5.45x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_tgp-a"
    ]
  },
  "wpn_saiga12s": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_scar": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_scar_custom": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_scar_new": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig220": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_45"
    ]
  },
  "wpn_sig220_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_45"
    ]
  },
  "wpn_sig550": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig550_camo": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig550_custom": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig550_luckygun": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig550_sniper": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sig552": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  },
  "wpn_sks": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ]
  },
  "wpn_sks_modern": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ]
  },
  "wpn_spas12": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_spas12_custom": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_spas12_nimble": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_sr25": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ],
    "gl": [
      "wpn_addon_grenade_launcher_m203",
      "ammo_m209",
      "ammo_m209_bad",
      "ammo_m209_verybad"
    ],
    "silencer": [
      "wpn_sil_sr25"
    ]
  },
  "wpn_sv98": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_sv98_custom": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svd": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svd_custom": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svt40": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svt40_modern": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svu": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svu_alt": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_svu_nimble": {
    "ammo": [
      "ammo_7.62x54_7h1",
      "ammo_7.62x54_7h1_bad",
      "ammo_7.62x54_7h1_verybad",
      "ammo_7.62x54_ap",
      "ammo_7.62x54_ap_bad",
      "ammo_7.62x54_ap_verybad",
      "ammo_7.62x54_7h14",
      "ammo_7.62x54_7h14_bad",
      "ammo_7.62x54_7h14_verybad"
    ]
  },
  "wpn_toz34": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_toz34_custom": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_toz34_decor": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_toz34_obrez": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_toz34_obrez_custom": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_toz34_obrez_decor": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_trg": {
    "ammo": [
      "ammo_magnum_300",
      "ammo_magnum_300_bad",
      "ammo_magnum_300_verybad"
    ]
  },
  "wpn_tt33": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_tt33_modern": {
    "ammo": [
      "ammo_7.62x25_p",
      "ammo_7.62x25_p_bad",
      "ammo_7.62x25_p_verybad",
      "ammo_7.62x25_ps",
      "ammo_7.62x25_ps_bad",
      "ammo_7.62x25_ps_verybad"
    ]
  },
  "wpn_type63": {
    "ammo": [
      "ammo_7.62x39_fmj",
      "ammo_7.62x39_fmj_bad",
      "ammo_7.62x39_fmj_verybad",
      "ammo_7.62x39_ap",
      "ammo_7.62x39_ap_bad",
      "ammo_7.62x39_ap_verybad"
    ]
  },
  "wpn_ump45": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_ump45_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ],
    "silencer": [
      "wpn_sil_gemtech"
    ]
  },
  "wpn_usas12": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_usp": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_usp_custom": {
    "ammo": [
      "ammo_11.43x23_fmj",
      "ammo_11.43x23_fmj_bad",
      "ammo_11.43x23_fmj_verybad",
      "ammo_11.43x23_hydro",
      "ammo_11.43x23_hydro_bad",
      "ammo_11.43x23_hydro_verybad"
    ]
  },
  "wpn_usp_match": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_val": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_addon_silencer"
    ]
  },
  "wpn_val_modern": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_addon_silencer"
    ]
  },
  "wpn_vihr": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_vihr"
    ]
  },
  "wpn_vintorez": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_addon_silencer"
    ]
  },
  "wpn_vintorez_alt": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_addon_silencer"
    ]
  },
  "wpn_vityaz": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_pbs1"
    ]
  },
  "wpn_vsk94": {
    "ammo": [
      "ammo_9x39_pab9",
      "ammo_9x39_pab9_bad",
      "ammo_9x39_pab9_verybad",
      "ammo_9x39_ap",
      "ammo_9x39_ap_bad",
      "ammo_9x39_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_9a91"
    ]
  },
  "wpn_vssk": {
    "ammo": [
      "ammo_12.7x55_fmj",
      "ammo_12.7x55_fmj_bad",
      "ammo_12.7x55_fmj_verybad",
      "ammo_12.7x55_ap",
      "ammo_12.7x55_ap_bad",
      "ammo_12.7x55_ap_verybad"
    ]
  },
  "wpn_vz61": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_vz61_alt": {
    "ammo": [
      "ammo_9x18_fmj",
      "ammo_9x18_fmj_bad",
      "ammo_9x18_fmj_verybad",
      "ammo_9x18_pmm",
      "ammo_9x18_pmm_bad",
      "ammo_9x18_pmm_verybad",
      "ammo_9x18_ap",
      "ammo_9x18_ap_bad",
      "ammo_9x18_ap_verybad"
    ]
  },
  "wpn_vz61_camo": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_vz61_freedom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_wa2000": {
    "ammo": [
      "ammo_7.62x51_fmj",
      "ammo_7.62x51_fmj_bad",
      "ammo_7.62x51_fmj_verybad",
      "ammo_7.62x51_ap",
      "ammo_7.62x51_ap_bad",
      "ammo_7.62x51_ap_verybad"
    ]
  },
  "wpn_walther": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_walther_custom": {
    "ammo": [
      "ammo_9x19_fmj",
      "ammo_9x19_fmj_bad",
      "ammo_9x19_fmj_verybad",
      "ammo_9x19_pbp",
      "ammo_9x19_pbp_bad",
      "ammo_9x19_pbp_verybad",
      "ammo_9x19_ap",
      "ammo_9x19_ap_bad",
      "ammo_9x19_ap_verybad"
    ]
  },
  "wpn_wincheaster1300": {
    "ammo": [
      "ammo_12x70_buck",
      "ammo_12x70_buck_bad",
      "ammo_12x70_buck_verybad",
      "ammo_12x76_zhekan",
      "ammo_12x76_zhekan_bad",
      "ammo_12x76_zhekan_verybad",
      "ammo_12x76_dart",
      "ammo_12x76_dart_bad",
      "ammo_12x76_dart_verybad",
      "ammo_12x70_buck_self"
    ]
  },
  "wpn_xm8": {
    "ammo": [
      "ammo_5.56x45_fmj",
      "ammo_5.56x45_fmj_bad",
      "ammo_5.56x45_fmj_verybad",
      "ammo_5.56x45_ss190",
      "ammo_5.56x45_ss190_bad",
      "ammo_5.56x45_ss190_verybad",
      "ammo_5.56x45_ap",
      "ammo_5.56x45_ap_bad",
      "ammo_5.56x45_ap_verybad"
    ],
    "silencer": [
      "wpn_sil_nato"
    ]
  }
};
