#!/usr/bin/env python3
"""Generate the editor's bundled vanilla anomaly id catalog.

Extracts anomaly-related IDs from bundled vanilla config files so the editor can
show searchable suggestions for anomaly/artifact outcome parameters.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

REPO_ROOT = Path(__file__).resolve().parents[1]
VANILLA_ROOT = REPO_ROOT / "Stalker Anomaly Vanilla Resources(FOR REFERENCE ONLY)" / "vanilla configs (for reference only)"
ANOMALY_SCRIPTS_ROOT = VANILLA_ROOT / "scripts"
LAND_NAMES_XML = VANILLA_ROOT / "text" / "eng" / "st_land_names.xml"
OUTPUT_PATH = REPO_ROOT / "tools" / "editor" / "src" / "lib" / "generated" / "anomaly-zone-catalog.ts"

FIELD_RE = re.compile(r"^\s*field_name\s*=\s*([^;]+)", re.IGNORECASE)
XML_STRING_RE = re.compile(r"<string\s+id=\"([^\"]+)\"[^>]*>\s*<text>(.*?)</text>\s*</string>", re.DOTALL)


@dataclass(frozen=True)
class CatalogEntry:
    value: str
    label: str
    keywords: tuple[str, ...]


def parse_land_name_strings() -> dict[str, str]:
    if not LAND_NAMES_XML.exists():
        return {}
    text = LAND_NAMES_XML.read_text(encoding="utf-8", errors="ignore")
    out: dict[str, str] = {}
    for match in XML_STRING_RE.finditer(text):
        key = match.group(1).strip()
        val = re.sub(r"\s+", " ", match.group(2).strip())
        out[key] = val
    return out


def parse_anomaly_ids() -> tuple[dict[str, str], set[str]]:
    field_names: dict[str, str] = {}
    zone_ids: set[str] = set()
    if not ANOMALY_SCRIPTS_ROOT.exists():
        return field_names, zone_ids

    for path in sorted(ANOMALY_SCRIPTS_ROOT.rglob("*anomal*.ltx")):
        rel_path = path.relative_to(ANOMALY_SCRIPTS_ROOT).as_posix()
        stem = path.stem
        if stem:
            zone_ids.add(stem)

        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            m = FIELD_RE.match(line)
            if m:
                raw_field_names = m.group(1).strip()
                for token in raw_field_names.split(","):
                    field_name = token.strip()
                    if not field_name:
                        continue
                    field_names[field_name] = rel_path
                break

    return field_names, zone_ids


def build_catalog() -> list[CatalogEntry]:
    land_names = parse_land_name_strings()
    field_names, zone_ids = parse_anomaly_ids()
    entries: list[CatalogEntry] = []

    for field_name in sorted(field_names):
        desc = land_names.get(f"st_{field_name}_name")
        base = f"Anomaly Spot — {desc}" if desc else "Anomaly Spot"
        keywords = [field_name, "anomaly", "spot"]
        if desc:
            keywords.append(desc)
        entries.append(CatalogEntry(
            value=field_name,
            label=f"{field_name} — {base}",
            keywords=tuple(keywords),
        ))

    for zone_id in sorted(zone_ids):
        if zone_id in field_names:
            continue
        desc = land_names.get(f"st_{zone_id}_spot_name") or land_names.get(f"st_{zone_id}_name")
        base = f"Anomaly Zone ID — {desc}" if desc else "Anomaly Zone ID"
        keywords = [zone_id, "anomaly", "zone", "task"]
        if desc:
            keywords.append(desc)
        entries.append(CatalogEntry(
            value=zone_id,
            label=f"{zone_id} — {base}",
            keywords=tuple(keywords),
        ))

    entries.sort(key=lambda e: e.value)
    return entries


def render_ts(entries: list[CatalogEntry]) -> str:
    header = """// P.A.N.D.A. Conversation Editor — Vanilla anomaly/artifact ID catalog
// Generated by tools/build_editor_anomaly_catalog.py from bundled Anomaly reference files.
// Do not edit by hand; refresh with `python tools/build_editor_anomaly_catalog.py`.

import type { ParamOption } from '../schema';

export const ANOMALY_ZONE_ID_OPTIONS: ParamOption[] = [
"""
    body = "\n".join(
        f"  {{ value: {entry.value!r}, label: {entry.label!r}, keywords: {list(entry.keywords)!r} }},"
        for entry in entries
    )
    return f"{header}{body}\n];\n"


def main() -> None:
    entries = build_catalog()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render_ts(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} anomaly ids to {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
