local SINGLETON = nil
function get_ui()
	SINGLETON = SINGLETON or pda_monolitch_hackers_tab()
	SINGLETON:Reset()
	return SINGLETON
end

class "pda_monolitch_hackers_tab" (CUIScriptWnd)
function pda_monolitch_hackers_tab:__init() super()
    self:InitControls()
end

function pda_monolitch_hackers_tab:InitControls()
    self:SetWndRect(Frect():set(0,0,1024,768))
	local xml               = CScriptXmlInit()
	xml:ParseFile("pda_errors.xml")
	self.picture			= xml:InitStatic("picture_base",self)
	self.picture:InitTexture ("ui\\ui_noise")
	self.text 			= xml:InitTextWnd("text_center", self)
	self.text:SetText(game.translate_string("st_pda_monolitch_hackers"))
    self.text:SetTextColor(GetARGB(255, 255, 255, 0))
end

function pda_monolitch_hackers_tab:Update()
	CUIScriptWnd.Update(self)
end

function pda_monolitch_hackers_tab:Reset()
end